//! Typed API extension surface and online helpers: the `extend` /
//! `extend_rest` entry points binding user-declared API structs to a chain's
//! transports (structs generated by the [`#[hive_api]`](crate::hive_api)
//! attribute), plus the online-only convenience methods — the
//! `create_transaction` factory, `broadcast` and the per-account manabar
//! accessors.

use crate::base::build_transaction_with_chain_reference_data;
use crate::models::basic::HiveDateTime;
use crate::models::enums::EManabarType;
use crate::{ManabarData, Transaction, WaxError};

use super::api::BroadcastTransactionRequest;
use super::broadcast::Broadcastable;
use super::error::WaxChainError;
use super::hive_chain::HiveChain;
use super::internal::manabar::manabar_arguments;
use super::online_transaction::OnlineTransaction;
use super::rest::RestCaller;
use super::rpc::JsonRpcCaller;

/// Provides construction of a typed JSON-RPC API surface bound to a chain's
/// transport. Implemented by the surfaces generated by
/// [`#[hive_api]`](crate::hive_api).
///
/// TS NOTE: the Rust analog of the `YourApi` type parameter of TS
/// `IHiveChainInterface.extend<YourApi>()`.
pub trait HiveApi {
    /// Builds the API surface bound to the given JSON-RPC transport.
    fn bind(caller: JsonRpcCaller) -> Self;
}

/// Provides construction of a typed REST API surface bound to a chain's
/// transport. Implemented by the surfaces generated by
/// [`#[hive_api(rest)]`](crate::hive_api).
///
/// TS NOTE: the Rust analog of the `YourRestApi` type parameter of TS
/// `extendRest<YourRestApi>()`.
pub trait HiveRestApi {
    /// Builds the API surface bound to the given REST transport.
    fn bind(caller: RestCaller) -> Self;
}

// The generic `extend` / `extend_rest` constructors and online helpers.
impl HiveChain {
    /// Builds the typed JSON-RPC API surface `A` bound to this chain.
    ///
    /// TS NOTE: mirrors `IHiveChainInterface.extend<YourApi>()`. TS `extend`
    /// returns *the chain* widened with an `api` field (`this & { api: ... }`);
    /// Rust returns the typed API surface as its own value — the chain and
    /// the API handle are separate objects sharing one transport, so a later
    /// `set_endpoint_url` on the chain is reflected by handles already handed
    /// out.
    pub fn extend<A: HiveApi>(&self) -> A {
        A::bind(self.json_rpc_caller())
    }

    /// Builds the typed REST API surface `A` bound to this chain.
    ///
    /// TS NOTE: mirrors `extendRest<YourRestApi>()`; see [`Self::extend`] for
    /// how the returned surface relates to the chain.
    pub fn extend_rest<A: HiveRestApi>(&self) -> A {
        A::bind(self.rest_caller())
    }

    /// Creates an online transaction anchored to the chain's current head
    /// block (TaPoS reference data and expiration), ready for operation
    /// pushing, signing and the chain-dependent checks of
    /// [`OnlineTransaction`].
    ///
    /// `expiration` accepts an absolute Hive timestamp or a `+N[s|m|h]`
    /// offset; `None` defaults to `+1m`.
    ///
    /// TS NOTE: `createTransaction(expirationTime?)`. Like TS
    /// (`acquireChainReferenceData`), the chain reference data is cached
    /// between calls for 3 s.
    pub async fn create_transaction(
        &self,
        expiration: impl Into<Option<String>>,
    ) -> Result<OnlineTransaction, WaxChainError> {
        let reference = self.acquire_chain_reference_data().await?;

        let tx = build_transaction_with_chain_reference_data(
            self.chain_id(),
            &reference.head_block_id,
            Some(reference.time),
            expiration.into().as_deref(),
        )?;

        Ok(OnlineTransaction::new(
            Transaction::from_rust(tx),
            self.api(),
        ))
    }

    /// Broadcasts `transaction` to the chain's JSON-RPC endpoint, with no
    /// block-age limit. Accepts every [`Broadcastable`] form:
    /// [`ApiTransaction`](crate::api::ApiTransaction) (posted as-is),
    /// [`Transaction`] (converted to its API form) and [`OnlineTransaction`]
    /// (which additionally runs
    /// [`OnlineTransaction::perform_on_chain_verification`] first).
    ///
    /// TS NOTE: `IHiveChainInterface.broadcast(transaction)` — posts
    /// `network_broadcast_api.broadcast_transaction` with
    /// `max_block_age: -1`.
    pub async fn broadcast(
        &self,
        transaction: &impl Broadcastable,
    ) -> Result<(), WaxChainError> {
        let trx = transaction.to_broadcast_form().await?;

        self.api()
            .network_broadcast_api
            .broadcast_transaction(BroadcastTransactionRequest {
                trx,
                max_block_age: -1,
            })
            .await?;

        Ok(())
    }

    /// Calculates the current value of `account`'s manabar of the given
    /// type, regenerated to the chain's current head-block time.
    ///
    /// TS NOTE:
    /// `calculateCurrentManabarValueForAccount(account, manabarType)`; the TS
    /// parameter defaults to `UPVOTE` — Rust callers pass the type
    /// explicitly (or `EManabarType::default()`).
    pub async fn calculate_current_manabar_value_for_account(
        &self,
        account: &str,
        manabar_type: EManabarType,
    ) -> Result<ManabarData, WaxChainError> {
        let args =
            manabar_arguments(&self.api(), account, manabar_type).await?;

        Ok(self.calculate_current_manabar_value(
            args.head_block_time,
            args.max_mana,
            args.current_mana,
            args.last_update_time,
        )?)
    }

    /// Calculates the time at which `account`'s manabar of the given type
    /// will be fully regenerated. A manabar with no capacity
    /// (`max_mana == 0`) is reported as regenerated now.
    ///
    /// TS NOTE:
    /// `calculateManabarFullRegenerationTimeForAccount(account, manabarType)`.
    pub async fn calculate_manabar_full_regeneration_time_for_account(
        &self,
        account: &str,
        manabar_type: EManabarType,
    ) -> Result<HiveDateTime, WaxChainError> {
        let args =
            manabar_arguments(&self.api(), account, manabar_type).await?;

        if args.max_mana == 0 {
            return Ok(HiveDateTime::now());
        }

        let timestamp = self.calculate_manabar_full_regeneration_time(
            args.head_block_time,
            args.max_mana,
            args.current_mana,
            args.last_update_time,
        )?;

        regeneration_date(timestamp)
    }
}

/// Converts a regeneration unix timestamp (seconds) into a [`HiveDateTime`].
///
/// NOTE: chrono bounds-checks the timestamp; TS `new Date(time * 1000)`
/// silently yields an invalid date instead.
fn regeneration_date(seconds: u64) -> Result<HiveDateTime, WaxChainError> {
    let date_time = i64::try_from(seconds)
        .ok()
        .and_then(|seconds| chrono::DateTime::from_timestamp(seconds, 0))
        .ok_or_else(|| {
            WaxError::new(format!(
                "Manabar regeneration timestamp {seconds} exceeds the \
                 supported date range"
            ))
        })?;

    Ok(HiveDateTime::new(date_time))
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use serde::{Deserialize, Serialize};
    use serde_json::{Value, json};

    use crate::hive_api;

    use super::super::rpc::JsonRpcClient;
    use super::super::util::test_support::spawn_capture_server;
    use super::*;

    #[derive(Serialize)]
    pub(crate) struct PingRequest {
        token: u32,
    }

    #[derive(Deserialize)]
    pub(crate) struct PingResponse {
        pong: u32,
    }

    /// Test namespace (`test_api`, inferred from the trait name).
    #[hive_api]
    pub(crate) trait TestApi {
        /// Sends a ping.
        async fn ping(params: PingRequest) -> PingResponse;
    }

    /// Extra test namespace.
    #[hive_api(namespace = "extra_api")]
    pub(crate) trait ExtraApi {
        /// Echoes the params.
        async fn echo(params: Value) -> Value;
    }

    /// Composed test surface.
    #[hive_api]
    pub(crate) struct ComposedApi {
        pub extra_api: ExtraApi,
        #[hive_api(base)]
        base: TestApi,
    }

    /// REST test surface.
    #[hive_api(rest, namespace = "hafah_api")]
    pub(crate) trait HafahApi {
        /// Fetches a transaction; `{transactionId}` comes from the params.
        #[get("/hafah-api/transactions/{transactionId}")]
        async fn get_transaction(params: Value) -> Value;

        /// Creates an item (verb + JSON body coverage).
        #[post("/items/{id}")]
        async fn make_item(params: Value) -> Value;
    }

    fn caller(endpoint: String) -> JsonRpcCaller {
        JsonRpcCaller::new(Arc::new(JsonRpcClient::new(
            endpoint, 5_000, None, None, None,
        )))
    }

    // TS NOTE: mirrors `ts/wasm/__tests__/detailed/hive_chain.ts` ('Should be
    // able to extend hive chain interface by custom definitions using
    // interfaces only') — a generated method must post a `"<ns>.<method>"`
    // JSON-RPC envelope and decode the typed result.
    #[tokio::test]
    async fn generated_method_posts_namespaced_json_rpc_call() {
        let (endpoint, captured) = spawn_capture_server(
            r#"{"jsonrpc":"2.0","id":1,"result":{"pong":7}}"#,
        );

        let api = TestApi::bind(caller(endpoint));
        let response = api.ping(PingRequest { token: 7 }).await.unwrap();

        assert_eq!(response.pong, 7);

        let raw = captured.recv().unwrap();
        let body_start = raw.find("\r\n\r\n").unwrap() + 4;
        let body: Value = serde_json::from_str(&raw[body_start..]).unwrap();

        assert_eq!(body["jsonrpc"], "2.0");
        assert_eq!(body["method"], "test_api.ping");
        assert_eq!(body["params"], json!({ "token": 7 }));
    }

    // The composition struct — own namespaces work and the base surface
    // stays reachable through the generated `Deref` (the Rust analog of the
    // TS `&` intersection).
    #[tokio::test]
    async fn composed_api_exposes_own_and_base_namespaces() {
        let (endpoint, captured) = spawn_capture_server(
            r#"{"jsonrpc":"2.0","id":1,"result":"marco"}"#,
        );

        let api = ComposedApi::bind(caller(endpoint));
        let echoed: Value = api.extra_api.echo(json!("marco")).await.unwrap();

        assert_eq!(echoed, json!("marco"));
        assert!(
            captured
                .recv()
                .unwrap()
                .contains(r#""method":"extra_api.echo""#)
        );

        // The capture server is single-shot; the base surface hit through
        // `Deref` needs its own binding.
        let (endpoint, captured) = spawn_capture_server(
            r#"{"jsonrpc":"2.0","id":1,"result":{"pong":1}}"#,
        );

        let api = ComposedApi::bind(caller(endpoint));
        api.ping(PingRequest { token: 1 }).await.unwrap();

        assert!(
            captured
                .recv()
                .unwrap()
                .contains(r#""method":"test_api.ping""#)
        );
    }

    // `extend` must resolve on a factory-built chain.
    #[tokio::test]
    async fn extends_chain() {
        let (endpoint, _captured) = spawn_capture_server(
            r#"{"jsonrpc":"2.0","id":1,"result":{"pong":3}}"#,
        );

        let chain = crate::create_hive_chain(crate::HiveChainOptions {
            api_endpoint: endpoint,
            ..Default::default()
        })
        .unwrap();

        let api = chain.extend::<TestApi>();
        let response = api.ping(PingRequest { token: 3 }).await.unwrap();

        assert_eq!(response.pong, 3);
    }

    // TS NOTE: mirrors `hive_chain_rest_api.ts` ('Should be able to extend
    // and perform REST API calls') — a generated REST method must substitute
    // `{placeholders}` from the params and send the rest as query string.
    #[tokio::test]
    async fn rest_method_substitutes_path_and_query_params() {
        let (endpoint, captured) =
            spawn_capture_server(r#"{"transaction_json":{"id":1}}"#);

        let chain = crate::create_hive_chain(crate::HiveChainOptions {
            rest_api_endpoint: endpoint,
            ..Default::default()
        })
        .unwrap();

        let rest = chain.extend_rest::<HafahApi>();
        let result = rest
            .get_transaction(
                json!({ "transactionId": "954f", "include-virtual": true }),
            )
            .await
            .unwrap();

        assert_eq!(result["transaction_json"], json!({ "id": 1 }));
        assert!(captured.recv().unwrap().starts_with(
            "GET /hafah-api/transactions/954f?include-virtual=true HTTP/1.1"
        ));
    }

    // The health-checker sugar: the generated descriptor consts must carry
    // the wire identity, and a generated `<name>_probe` bundle must drive a
    // real check round end to end.
    #[tokio::test]
    async fn generated_probe_registers_with_the_health_checker() {
        assert_eq!(TestApi::PING.method, "test_api.ping");
        assert_eq!(TestApi::PING.namespace_path, ["test_api", "ping"]);
        assert_eq!(HafahApi::GET_TRANSACTION.method, "GET");
        assert_eq!(
            HafahApi::GET_TRANSACTION.namespace_path,
            ["hafah_api", "get_transaction"]
        );

        let (endpoint, captured) = spawn_capture_server(
            r#"{"jsonrpc":"2.0","id":1,"result":{"pong":9}}"#,
        );

        let api = TestApi::bind(caller("http://127.0.0.1:1".into()));
        let checker = crate::HealthChecker::new();
        let handle = checker.register_with_validator(
            api.ping_probe(PingRequest { token: 9 }),
            |response: &PingResponse| {
                if response.pong == 9 {
                    Ok(())
                } else {
                    Err("wrong pong".into())
                }
            },
            vec![endpoint.clone()],
        );

        assert_eq!(handle.api_caller_id(), crate::ChainApiType::JsonRpc);
        assert_eq!(handle.paths(), ["test_api", "ping"]);

        checker.perform_checks().await;

        // The probe must hit the checked URL (not the caller's endpoint)
        // and a passing validator must score it up.
        assert!(
            captured
                .recv()
                .unwrap()
                .contains(r#""method":"test_api.ping""#)
        );
        assert_eq!(checker.best(), Some(endpoint));
    }

    // TS NOTE: mirrors `api.hafah_api.endpointUrl = url` — the generated
    // per-namespace setter must route this namespace's calls on both
    // transports. The chain defaults are unroutable, so the calls only
    // succeed through the override.
    #[tokio::test]
    async fn generated_set_endpoint_url_overrides_namespace_endpoint() {
        let (endpoint, captured) = spawn_capture_server(r#"{"ok":true}"#);

        let chain = crate::create_hive_chain(crate::HiveChainOptions {
            rest_api_endpoint: "http://127.0.0.1:1".into(),
            ..Default::default()
        })
        .unwrap();

        let rest = chain.extend_rest::<HafahApi>();
        rest.set_endpoint_url(Some(endpoint));
        rest.make_item(json!({ "id": 1 })).await.unwrap();

        assert!(captured.recv().unwrap().starts_with("POST /items/1"));

        // The JSON-RPC side carries the same surface.
        let (endpoint, captured) = spawn_capture_server(
            r#"{"jsonrpc":"2.0","id":1,"result":{"pong":5}}"#,
        );

        let api = TestApi::bind(caller("http://127.0.0.1:1".into()));
        api.set_endpoint_url(Some(endpoint));
        api.ping(PingRequest { token: 5 }).await.unwrap();

        assert!(
            captured
                .recv()
                .unwrap()
                .contains(r#""method":"test_api.ping""#)
        );

        // Clearing the override falls back to the (unroutable) default.
        api.set_endpoint_url(None);
        assert!(api.ping(PingRequest { token: 5 }).await.is_err());
    }

    #[tokio::test]
    async fn rest_method_posts_remaining_params_as_body() {
        let (endpoint, captured) = spawn_capture_server(r#"{"ok":true}"#);

        let chain = crate::create_hive_chain(crate::HiveChainOptions {
            rest_api_endpoint: endpoint,
            ..Default::default()
        })
        .unwrap();

        let rest = chain.extend_rest::<HafahApi>();
        rest.make_item(json!({ "id": 7, "name": "widget" }))
            .await
            .unwrap();

        let raw = captured.recv().unwrap();

        assert!(raw.starts_with("POST /items/7 HTTP/1.1"));
        assert!(raw.ends_with(r#"{"name":"widget"}"#));
    }

    // TS NOTE: mirrors `chain.broadcast(tx)` with an `ApiTransaction` — the
    // helper must post `network_broadcast_api.broadcast_transaction` with
    // `max_block_age: -1` and the transaction as `trx`.
    #[tokio::test]
    async fn broadcast_posts_with_unlimited_block_age() {
        let (endpoint, captured) =
            spawn_capture_server(r#"{"jsonrpc":"2.0","id":1,"result":{}}"#);

        let chain = crate::create_hive_chain(crate::HiveChainOptions {
            api_endpoint: endpoint,
            ..Default::default()
        })
        .unwrap();

        let trx = crate::api::ApiTransaction {
            ref_block_num: 0x578e,
            ref_block_prefix: 0x6dcf_900a,
            expiration: "2025-07-08T12:35:57".parse().unwrap(),
            operations: Vec::new(),
            extensions: Vec::new(),
            signatures: Vec::new(),
        };
        chain.broadcast(&trx).await.unwrap();

        let raw = captured.recv().unwrap();
        let body_start = raw.find("\r\n\r\n").unwrap() + 4;
        let body: Value = serde_json::from_str(&raw[body_start..]).unwrap();

        assert_eq!(
            body["method"],
            "network_broadcast_api.broadcast_transaction"
        );
        assert_eq!(body["params"]["max_block_age"], json!(-1));
        assert_eq!(body["params"]["trx"]["ref_block_num"], json!(0x578e));
        assert_eq!(body["params"]["trx"]["signatures"], json!([]));
    }

    // The `options()` snapshot + struct-update syntax is the Rust form of TS
    // `extendConfig(config)` — a derived chain with selective overrides.
    #[test]
    fn options_snapshot_derives_reconfigured_chain() {
        let chain = crate::create_hive_chain(crate::HiveChainOptions {
            api_endpoint: "http://127.0.0.1:1/".into(),
            api_timeout: 1_234,
            ..Default::default()
        })
        .unwrap();
        chain.set_endpoint_url("http://127.0.0.1:2/").unwrap();

        let derived = crate::create_hive_chain(crate::HiveChainOptions {
            chain_id: "42".repeat(32),
            ..chain.options()
        })
        .unwrap();

        assert_eq!(derived.chain_id(), "42".repeat(32));
        // The snapshot carries the live endpoint, not the constructed one.
        assert_eq!(derived.endpoint_url(), "http://127.0.0.1:2/");
        assert_eq!(derived.options().api_timeout, 1_234);
        assert_eq!(derived.rest_endpoint_url(), chain.rest_endpoint_url());
    }
}
