//! Typed API extension surface: the `extend` / `extend_rest` entry points
//! binding user-declared API structs to a chain's transports. The structs
//! are generated by the [`#[hive_api]`](crate::hive_api) attribute.

use super::hive_chain::HiveChain;
use super::rest::RestCaller;
use super::rpc::JsonRpcCaller;

/// Provides construction of a typed JSON-RPC API surface bound to a chain's
/// transport. Implemented by the surfaces generated by
/// [`#[hive_api]`](crate::hive_api).
///
/// TS NOTE: the Rust analog of the `YourApi` type parameter of TS
/// `IHiveChainInterface.extend<YourApi>()`.
pub trait HiveApi {
    /// Builds the API surface bound to the given JSON-RPC transport.
    fn bind(caller: JsonRpcCaller) -> Self;
}

/// Provides construction of a typed REST API surface bound to a chain's
/// transport. Implemented by the surfaces generated by
/// [`#[hive_api(rest)]`](crate::hive_api).
///
/// TS NOTE: the Rust analog of the `YourRestApi` type parameter of TS
/// `extendRest<YourRestApi>()`.
pub trait HiveRestApi {
    /// Builds the API surface bound to the given REST transport.
    fn bind(caller: RestCaller) -> Self;
}

/// Provides the generic `extend` / `extend_rest` constructors on every chain.
///
/// TS NOTE: mirrors `IHiveChainInterface.extend<YourApi>()` /
/// `extendRest<YourRestApi>()`. Lives in a non-object-safe extension trait so
/// the generic methods don't break `dyn HiveChain` object safety; the blanket
/// impl makes them callable on every [`HiveChain`], including
/// `Box<dyn HiveChain>`.
///
/// TS NOTE: TS `extend` returns *the chain* widened with an `api` field
/// (`this & { api: ... }`); Rust returns the typed API surface as its own
/// value — the chain and the API handle are separate objects sharing one
/// transport, so a later `set_endpoint_url` on the chain is reflected by
/// handles already handed out.
pub trait HiveChainExt: HiveChain {
    /// Builds the typed JSON-RPC API surface `A` bound to this chain.
    fn extend<A: HiveApi>(&self) -> A {
        A::bind(self.json_rpc_caller())
    }

    /// Builds the typed REST API surface `A` bound to this chain.
    fn extend_rest<A: HiveRestApi>(&self) -> A {
        A::bind(self.rest_caller())
    }
}

impl<T: HiveChain + ?Sized> HiveChainExt for T {}

#[cfg(test)]
mod tests {
    use std::sync::Arc;
    use std::time::Duration;

    use serde::{Deserialize, Serialize};
    use serde_json::{Value, json};

    use crate::hive_api;

    use super::super::rpc::JsonRpcClient;
    use super::super::util::test_support::spawn_capture_server;
    use super::*;

    #[derive(Serialize)]
    pub(crate) struct PingRequest {
        token: u32,
    }

    #[derive(Deserialize)]
    pub(crate) struct PingResponse {
        pong: u32,
    }

    /// Test namespace (`test_api`, inferred from the trait name).
    #[hive_api]
    pub(crate) trait TestApi {
        /// Sends a ping.
        async fn ping(params: PingRequest) -> PingResponse;
    }

    /// Extra test namespace.
    #[hive_api(namespace = "extra_api")]
    pub(crate) trait ExtraApi {
        /// Echoes the params.
        async fn echo(params: Value) -> Value;
    }

    /// Composed test surface.
    #[hive_api]
    pub(crate) struct ComposedApi {
        pub extra_api: ExtraApi,
        #[hive_api(base)]
        base: TestApi,
    }

    /// REST test surface.
    #[hive_api(rest, namespace = "hafah_api")]
    pub(crate) trait HafahApi {
        /// Fetches a transaction; `{transactionId}` comes from the params.
        #[get("/hafah-api/transactions/{transactionId}")]
        async fn get_transaction(params: Value) -> Value;

        /// Creates an item (verb + JSON body coverage).
        #[post("/items/{id}")]
        async fn make_item(params: Value) -> Value;
    }

    fn caller(endpoint: String) -> JsonRpcCaller {
        JsonRpcCaller::new(Arc::new(
            JsonRpcClient::new(endpoint, Duration::from_secs(5)).unwrap(),
        ))
    }

    // TS NOTE: mirrors `ts/wasm/__tests__/detailed/hive_chain.ts` ('Should be
    // able to extend hive chain interface by custom definitions using
    // interfaces only') — a generated method must post a `"<ns>.<method>"`
    // JSON-RPC envelope and decode the typed result.
    #[tokio::test]
    async fn generated_method_posts_namespaced_json_rpc_call() {
        let (endpoint, captured) = spawn_capture_server(
            r#"{"jsonrpc":"2.0","id":1,"result":{"pong":7}}"#,
        );

        let api = TestApi::bind(caller(endpoint));
        let response = api.ping(PingRequest { token: 7 }).await.unwrap();

        assert_eq!(response.pong, 7);

        let raw = captured.recv().unwrap();
        let body_start = raw.find("\r\n\r\n").unwrap() + 4;
        let body: Value = serde_json::from_str(&raw[body_start..]).unwrap();

        assert_eq!(body["jsonrpc"], "2.0");
        assert_eq!(body["method"], "test_api.ping");
        assert_eq!(body["params"], json!({ "token": 7 }));
    }

    // The composition struct — own namespaces work and the base surface
    // stays reachable through the generated `Deref` (the Rust analog of the
    // TS `&` intersection).
    #[tokio::test]
    async fn composed_api_exposes_own_and_base_namespaces() {
        let (endpoint, captured) = spawn_capture_server(
            r#"{"jsonrpc":"2.0","id":1,"result":"marco"}"#,
        );

        let api = ComposedApi::bind(caller(endpoint));
        let echoed: Value = api.extra_api.echo(json!("marco")).await.unwrap();

        assert_eq!(echoed, json!("marco"));
        assert!(
            captured
                .recv()
                .unwrap()
                .contains(r#""method":"extra_api.echo""#)
        );

        // The capture server is single-shot; the base surface hit through
        // `Deref` needs its own binding.
        let (endpoint, captured) = spawn_capture_server(
            r#"{"jsonrpc":"2.0","id":1,"result":{"pong":1}}"#,
        );

        let api = ComposedApi::bind(caller(endpoint));
        api.ping(PingRequest { token: 1 }).await.unwrap();

        assert!(
            captured
                .recv()
                .unwrap()
                .contains(r#""method":"test_api.ping""#)
        );
    }

    // `extend` must resolve on `Box<dyn HiveChain>` via the blanket impl.
    #[tokio::test]
    async fn extends_chain_trait_object() {
        let (endpoint, _captured) = spawn_capture_server(
            r#"{"jsonrpc":"2.0","id":1,"result":{"pong":3}}"#,
        );

        let chain = crate::create_hive_chain(crate::WaxChainOptions {
            api_endpoint: endpoint,
            ..Default::default()
        })
        .unwrap();

        let api = chain.extend::<TestApi>();
        let response = api.ping(PingRequest { token: 3 }).await.unwrap();

        assert_eq!(response.pong, 3);
    }

    // TS NOTE: mirrors `hive_chain_rest_api.ts` ('Should be able to extend
    // and perform REST API calls') — a generated REST method must substitute
    // `{placeholders}` from the params and send the rest as query string.
    #[tokio::test]
    async fn rest_method_substitutes_path_and_query_params() {
        let (endpoint, captured) =
            spawn_capture_server(r#"{"transaction_json":{"id":1}}"#);

        let chain = crate::create_hive_chain(crate::WaxChainOptions {
            rest_api_endpoint: endpoint,
            ..Default::default()
        })
        .unwrap();

        let rest = chain.extend_rest::<HafahApi>();
        let result = rest
            .get_transaction(
                json!({ "transactionId": "954f", "include-virtual": true }),
            )
            .await
            .unwrap();

        assert_eq!(result["transaction_json"], json!({ "id": 1 }));
        assert!(captured.recv().unwrap().starts_with(
            "GET /hafah-api/transactions/954f?include-virtual=true HTTP/1.1"
        ));
    }

    #[tokio::test]
    async fn rest_method_posts_remaining_params_as_body() {
        let (endpoint, captured) = spawn_capture_server(r#"{"ok":true}"#);

        let chain = crate::create_hive_chain(crate::WaxChainOptions {
            rest_api_endpoint: endpoint,
            ..Default::default()
        })
        .unwrap();

        let rest = chain.extend_rest::<HafahApi>();
        rest.make_item(json!({ "id": 7, "name": "widget" }))
            .await
            .unwrap();

        let raw = captured.recv().unwrap();

        assert!(raw.starts_with("POST /items/7 HTTP/1.1"));
        assert!(raw.ends_with(r#"{"name":"widget"}"#));
    }
}
