use rust_decimal::Decimal;

use crate::WaxError;
use crate::base::models::authority::AccountAuthorityInfo;
use crate::base::models::basic::{PublicKey, Signature};

/// Provides read access to an account's mana pool and its computed percentage.
pub trait Manabar {
    /// Returns the maximum mana of the pool.
    fn max_mana(&self) -> i64;
    /// Returns the current mana of the pool.
    fn current_mana(&self) -> i64;
    /// Returns the current mana as a percentage of the maximum.
    fn percent(&self) -> Decimal;
}

/// Provides account authorities and witness signing keys to the offline
/// signing helpers.
pub trait AuthorityDataProvider {
    /// Returns the authority information for the given account.
    fn get_account_authorities(
        &self,
        account: &str,
    ) -> Result<AccountAuthorityInfo, WaxError>;

    /// Returns the witness's public signing key, if known.
    fn get_witness_public_key(
        &self,
        _witness: &str,
    ) -> Result<Option<PublicKey>, WaxError> {
        Ok(None)
    }
}

/// Provides digest signing and memo-style data encryption. Implementors hold
/// private keys or proxy a wallet daemon.
pub trait SignatureProvider {
    /// Sign a transaction `sig_digest` with the private key matching `public_key`.
    ///
    /// `public_key` is a WIF-format key string; `sig_digest` is a hex string
    /// produced by [`crate::Transaction::sig_digest`] (or its legacy variant).
    fn sign_digest(
        &self,
        public_key: &str,
        sig_digest: &str,
    ) -> Result<Signature, WaxError>;

    /// Encrypt `content` for the holder of `key` (and optionally `other_key`,
    /// when the message is also addressed to a third party).
    ///
    /// `nonce` may be passed to make encryption deterministic; otherwise a
    /// fresh nonce is generated by the provider. The returned string is a
    /// base58-encoded encrypted buffer suitable for use as a memo payload.
    fn encrypt_data(
        &self,
        content: &str,
        key: &str,
        other_key: Option<&str>,
        nonce: Option<u64>,
    ) -> Result<String, WaxError>;

    /// Decrypt a base58-encoded buffer previously produced by [`Self::encrypt_data`].
    ///
    /// `key` (and optionally `other_key`) identifies which private key(s) in
    /// the underlying container should be used to decrypt the payload.
    fn decrypt_data(
        &self,
        content: &str,
        key: &str,
        other_key: Option<&str>,
    ) -> Result<String, WaxError>;
}

// NOTE: the transaction and operation types are the concrete
// [`Transaction`](crate::Transaction) / [`Operation`](crate::Operation)
// structs (`base::transaction`, `base::operation`) — layered concrete types
// replaced the former object-safe traits. `ComplexOperation` lives with
// `Operation` in `base::operation`.
