stages:
  - build
  - test
  - deploy

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  # uses registry.gitlab.syncad.com/hive/hive/ci-base-image:ubuntu22.04-7
  CI_BASE_IMAGE_TAG: "@sha256:8f68baf07c6e581e1e8034a1447c4ff1268239fc886bfe4b02aa3f4182bf78bb"
  CI_BASE_IMAGE: "registry.gitlab.syncad.com/hive/hive/ci-base-image${CI_BASE_IMAGE_TAG}"
  # colors:
  TXT_BLUE: "\e[1;34m"
  TXT_CLEAR: "\e[0m"
  NPM_TOKEN: $CI_JOB_TOKEN

include:
  - project: 'hive/common-ci-configuration'
    ref: ae2ec71af47184cdd9567ae85ff821d133c3343f
    file:
      - '/templates/wasm_build.gitlab-ci.yml'
      - '/templates/python_projects.gitlab-ci.yml'

image: "${CI_BASE_IMAGE}"

default:
  tags:
    - public-runner-docker

.configuration:
  before_script:
    - python3 -V
    - poetry self add poetry-grpc-plugin@0.1.7
    - poetry self add "poetry-dynamic-versioning[plugin]"
    - poetry self update
    - pip list
  tags:
    - public-runner-docker

build_wheel:
  extends: .build_wheel_template
  before_script:
    - !reference [.build_wheel_template, before_script]
    - git fetch --tags --force
    - rm -rf dist/
    - poetry build --format wheel
    - ls -al dist/
  needs:
    - job: wax_proto_python_generation
      artifacts: true
  artifacts:
    when: always
    paths:
      - "dist/"
      - ".build/logs/"
      - ".build/*.so"
      - "build_wheel.env"
    reports:
      dotenv: "build_wheel.env"


wax_wasm_build:
  extends: .wasm_build_job_template
  stage: build
  variables:
    SOURCE_DIR: "${CI_PROJECT_DIR}/wasm/src/"
    BINARIES_DIR: "${CI_PROJECT_DIR}/build_wasm"
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/build_wasm/wax_wasm.js"
      - "$CI_PROJECT_DIR/build_wasm/wax_wasm.wasm"
      - "$CI_PROJECT_DIR/build_wasm/wax.d.ts"

wax_wasm_package_generation:
  stage: build
  # emscripten image can be used as it contains all needed tools.
  image: ${EMSCRIPTEN_IMAGE}
  variables:
    PUBLISH_TOKEN: "$NPM_TOKEN"
    NPM_SCOPE: "@hive"
    NPM_REGISTRY: "gitlab.syncad.com/api/v4/packages/npm/"
  script:
    - scripts/bump_npm_version.sh "$PUBLISH_TOKEN" "$NPM_SCOPE" "$NPM_REGISTRY"
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/.npmrc"
      - "$CI_PROJECT_DIR/package.json"

    when: always
    expire_in: 1 week

  tags:
    - public-runner-docker

wax_proto_python_generation:
  stage: build
  extends: .configuration
  script:
    - scripts/compile_proto_python.sh
  artifacts:
    paths:
      - "wax/proto"
    when: always
  tags:
    - public-runner-docker

wax_wasm_proto_tsc_generation:
  stage: build
  # emscripten image can be used as it contains all needed tools.
  image: ${EMSCRIPTEN_IMAGE}
  script:
    - pnpm install # we actually want to move to yarn
    - npm run build
  needs:
    - job: wax_wasm_build
      artifacts: true
    - job: wax_wasm_package_generation
      artifacts: true
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/wasm/dist"

    when: always
    expire_in: 1 week

  tags:
    - public-runner-docker

.test_python_env:
  stage: test
  extends: .configuration_template
  needs:
    - job: build_wheel
      artifacts: true
  before_script:
    - poetry env use python3
    - source $(poetry env info --path)/bin/activate
    - pip install dist/*.whl
    - pip list
    - ls -al $(poetry env info --path)/lib/python3.10/site-packages/
    - cd ..  # needed to import installed package instead of local one

test_importing_wax:
  extends: .test_python_env
  script:
    - echo -e "${TXT_BLUE}Testing...${TXT_CLEAR}"
    - python3 -c "import wax; print(wax.__version__)"

test_wax_protobuf_python:
  extends: .test_python_env
  script:
    - echo -e "${TXT_BLUE}Testing wax with proto ...${TXT_CLEAR}"
    - pytest /builds/hive/wax/wax/tests/

test_wax_protobuf_python_pattern:
  extends: .test_python_env
  needs:
    - job: build_wheel
      artifacts: true
    - job: wax_proto_python_generation
      artifacts: true
  script:
    - echo -e "${TXT_BLUE}Testing generated proto files with patterns ...${TXT_CLEAR}"
    - diff --brief --recursive --color=never --no-ignore-file-name-case --no-dereference  $CI_PROJECT_DIR/samples/python/proto/ $CI_PROJECT_DIR/wax/proto/
  artifacts:
    paths:
      - $CI_PROJECT_DIR/wax/proto/
 
    when: always
    expire_in: 1 week

test_wax_protobuf_python_examples:
  extends: .test_python_env
  script:
    - echo -e "${TXT_BLUE}Testing visitor of wax protobuf...${TXT_CLEAR}"
    - python3 /builds/hive/wax/examples/python/visitor_example.py

.wasm_wax_test_base:
  stage: test
  # emscripten image can be used as it contains all needed tools (node and npm).
  image: ${EMSCRIPTEN_IMAGE}
  variables:
    FF_NETWORK_PER_BUILD: 1

  interruptible: true

  before_script:
    - pnpm install

  tags:
    - public-runner-docker

test_wax_wasm:
  extends: .wasm_wax_test_base
  needs:
    - job: wax_wasm_build
      artifacts: true
    - job: wax_wasm_package_generation
      artifacts: true
  script:
    - npm run test
  artifacts:
    reports:
      junit: results.xml
    paths:
      - "$CI_PROJECT_DIR/results.json"

test_wax_wasm_proto_pattern:
  extends: .wasm_wax_test_base
  needs:
    - job: wax_wasm_build
      artifacts: true
    - job: wax_wasm_package_generation
      artifacts: true
    - job: wax_wasm_proto_tsc_generation
      artifacts: true

  script:
    - diff --brief --recursive --color=never --no-ignore-file-name-case --no-dereference "$CI_PROJECT_DIR/samples/ts/proto" "$CI_PROJECT_DIR/wasm/dist/proto"
    - npm pack --dry-run --json | jq -r '.[0]["files"][]["path"]' > $CI_PROJECT_DIR/wasm/dist/npm-pack.gen
    - diff --brief --color=never --no-dereference "$CI_PROJECT_DIR/wasm/dist/npm-pack.gen" "$CI_PROJECT_DIR/samples/ts/npm-pack.out"
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/wasm/dist"

    when: always
    expire_in: 1 week

test_wax_wasm_examples:
  extends: .wasm_wax_test_base
  needs:
    - job: wax_wasm_build
      artifacts: true
    - job: wax_wasm_package_generation
      artifacts: true
    - job: wax_wasm_proto_tsc_generation
      artifacts: true

  script:
    - npm run examples

.deploy_wheel_needs: &deploy_wheel_needs
  needs:
    - job: test_importing_wax
    - job: test_wax_protobuf_python
    - job: build_wheel
      artifacts: true

deploy_wheel_to_gitlab:
  stage: deploy
  extends: .deploy_wheel_to_gitlab_template
  <<: *deploy_wheel_needs

deploy_wheel_to_pypi:
  extends: .deploy_wheel_to_pypi_template
  stage: deploy
  <<: *deploy_wheel_needs

deploy_wax_wasm_dev_package:
  stage: deploy
  # emscripten image can be used as it contains all needed tools.
  image: ${EMSCRIPTEN_IMAGE}
  variables:
    PUBLISH_TOKEN: "$NPM_TOKEN"
    NPM_SCOPE: "@hive"
    NPM_REGISTRY: "gitlab.syncad.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/"

  script:
    - scripts/bump_npm_version.sh "$PUBLISH_TOKEN" "$NPM_SCOPE" "$NPM_REGISTRY"
    - scripts/npm_publish.sh
  needs:
    - job: test_wax_wasm_examples
    - job: test_wax_wasm
    - job: test_wax_wasm_proto_pattern
    - job: wax_wasm_proto_tsc_generation
      artifacts: true
    - job: wax_wasm_build
      artifacts: true

deploy_wax_wasm_production_public_npm:
  stage: deploy
  # emscripten image can be used as it contains all needed tools.
  image: ${EMSCRIPTEN_IMAGE}
  variables:
    PUBLISH_TOKEN: "$INTERNAL_HIDDEN_PUBLISH_TOKEN" # Add token variable here
    NPM_SCOPE: "@hive-staging"
    NPM_REGISTRY: "registry.npmjs.org/"
  script:
    - scripts/bump_npm_version.sh "$PUBLISH_TOKEN" "$NPM_SCOPE" "$NPM_REGISTRY"
    - scripts/npm_publish.sh
  needs:
    - job: wax_wasm_build
      artifacts: true
    - job: wax_wasm_proto_tsc_generation
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
      when: manual
      allow_failure: true
