image: registry.gitlab.syncad.com/hive/hive/ci-base-image:ubuntu22.04-3

stages:
  - build
  - test
  - tag
  - build_production
  - deploy

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  # colors:
  TXT_BLUE: "\e[1;34m"
  TXT_CLEAR: "\e[0m"
  NPM_TOKEN: $CI_JOB_TOKEN

  # uses registry.gitlab.syncad.com/hive/common-ci-configuration/emsdk:1d271c28906d267c1172641bb2aa42727f16b513
  EMSCRIPTEN_IMAGE_TAG: "@sha256:14287297ffbb7a55d134f1ab326f67aa8b387151f5118b21bf68e74ff1d437ed"

.shared_tags: &shared_tags
  - hived-for-tests

.configuration:
  before_script:
    - python3 -V
    - poetry self update
    - poetry self add "poetry-dynamic-versioning[plugin]"
    - pip list
  tags: *shared_tags

.build_wheel_base:
  extends: .configuration
  script:
    - echo -e "${TXT_BLUE}Building wheel...${TXT_CLEAR}"
    - git fetch --tags --force
    - rm -rf dist/
    - poetry build --format wheel
    - ls -al dist/
  artifacts:
    when: always
    paths:
      - "dist/"
      - ".build/logs/"
      - ".build/*.so"

build_wheel:
  stage: build
  extends: .build_wheel_base

wax_wasm_build:
  stage: build
  image: registry.gitlab.syncad.com/hive/common-ci-configuration/emsdk:3.1.43$EMSCRIPTEN_IMAGE_TAG
  interruptible: true
  variables:
    BINARIES_DIR: "build_wasm"
  script:
    - echo "Building Wax tool WASM version"
    - git config --global --add safe.directory '*'
    - mkdir -vp "$CI_PROJECT_DIR/$BINARIES_DIR"
    - cd "$CI_PROJECT_DIR/$BINARIES_DIR"
    - cmake -DBoost_NO_WARN_NEW_VERSIONS=1 -DBoost_USE_STATIC_RUNTIME=ON -DCMAKE_TOOLCHAIN_FILE=/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -S "$CI_PROJECT_DIR/wasm/src/" -B "$CI_PROJECT_DIR/$BINARIES_DIR"
    - make -j 8
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/package.json"
      - "$CI_PROJECT_DIR/$BINARIES_DIR/wax.d.ts"
      - "$CI_PROJECT_DIR/$BINARIES_DIR/wax_wasm.mjs"
      - "$CI_PROJECT_DIR/$BINARIES_DIR/wax_wasm.wasm"

    when: always
    expire_in: 1 week

  tags:
    - public-runner-docker
    - hived-for-tests

wax_wasm_package_generation:
  stage: build
  image: docker:latest
  before_script:
    - apk add jq git
  script:
    - scripts/bump_npm_version.sh
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/package.json"

    when: always
    expire_in: 1 week

  tags:
    - public-runner-docker
    - hived-for-tests

test_importing_wax:
  stage: test
  extends: .configuration
  needs:
    - job: build_wheel
      artifacts: true
  script:
    - echo -e "${TXT_BLUE}Testing...${TXT_CLEAR}"
    - poetry env use python3
    - source $(poetry env info --path)/bin/activate
    - pip install dist/*.whl
    - pip list
    - ls -al $(poetry env info --path)/lib/python3.10/site-packages/
    - cd ..  # needed to import installed package instead of local one
    - python3 -c "import wax; print(wax.__version__)"

test_wax_wasm:
  stage: test
  image: node:16-alpine
  interruptible: true
  needs:
    - job: wax_wasm_build
      artifacts: true
  tags: *shared_tags
  script:
    - cd "$CI_PROJECT_DIR/wasm/wax_wasm_test"
    - node run_node.mjs

tag_production:
  stage: tag
  extends: .configuration
  only:
    - master
    - develop
  script:
    - echo -e "${TXT_BLUE}Tagging job starting...${TXT_CLEAR}"
    - git remote set-url origin "https://oauth2:${GITLAB_TOKEN}@${CI_REPOSITORY_URL#*@}"
    - echo -e "${TXT_BLUE}Raw version from 'poetry version' is...${TXT_CLEAR}" && poetry version
    - if [[ "$CI_COMMIT_BRANCH" == "master" ]]; then
        VERSION_TAG="v$(poetry version patch -s)";
      else
        VERSION_TAG="v$(poetry version prerelease -s)";
      fi
    - echo -e "${TXT_BLUE}Current tags are...${TXT_CLEAR}" && git show-ref --tags
    - echo -e "${TXT_BLUE}New tag will be '${VERSION_TAG}'${TXT_CLEAR}"
    - git tag "${VERSION_TAG}"
    - git push -o ci.skip origin "${VERSION_TAG}"

build_wheel_production:
  stage: build_production
  extends: .build_wheel_base
  only:
    - master
    - develop
  variables:
    WAX_SKIP_BUILD: 1

.deploy_base:
  stage: deploy
  extends: .configuration
  script:
    - echo -e "${TXT_BLUE}Deploying...${TXT_CLEAR}"
    - ls -al dist/
    - poetry config repositories.gitlab "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
    - poetry config http-basic.gitlab gitlab-ci-token "${CI_JOB_TOKEN}"
    - poetry publish --repository gitlab

deploy_feature_branch:
  extends: .deploy_base
  needs:
    - job: test_importing_wax
    - job: build_wheel
      artifacts: true
  when: manual
  allow_failure: true
  except:
    - master
    - develop

deploy_production:
  extends: .deploy_base
  needs:
    - job: test_importing_wax
    - job: build_wheel_production
      artifacts: true
  only:
    - master
    - develop

deploy_wax_wasm_production:
  stage: deploy
  image: node:16-alpine
  script:
    - npm publish
  needs:
    - job: wax_wasm_build
      artifacts: true
    - job: wax_wasm_package_generation
      artifacts: true
  tags: *shared_tags
