image: registry.gitlab.syncad.com/hive/hive/ci-base-image:ubuntu22.04-3

stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # colors:
  TXT_BLUE: "\e[1;34m"
  TXT_CLEAR: "\e[0m"

.shared_tags: &shared_tags
  - hived-for-tests

.configuration:
  before_script:
    - python3 -V
    - poetry self update
    - poetry self add "poetry-dynamic-versioning[plugin]"
    - pip list
  tags: *shared_tags

build_wheel:
  stage: build
  extends: .configuration
  script:
    - echo -e "${TXT_BLUE}Building wheel...${TXT_CLEAR}"
    - poetry build --format wheel
    - ls -al dist/
  artifacts:
    when: always
    paths:
      - "dist/"
      - ".build/logs/"
  tags: *shared_tags

deploy:
  stage: deploy
  needs:
    - job: build_wheel
      artifacts: true
  extends: .configuration
  script:
    - echo -e "${TXT_BLUE}Deploying...${TXT_CLEAR}"
    - poetry config repositories.gitlab https://gitlab.syncad.com/api/v4/projects/419/packages/pypi/simple
    - poetry config http-basic.gitlab gitlab-ci-token "${CI_JOB_TOKEN}"
    - poetry publish --repository gitlab
  tags: *shared_tags
