# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: author_reward.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61uthor_reward.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto\"\x85\x03\n\rauthor_reward\x12\x0e\n\x06\x61uthor\x18\x01 \x02(\t\x12\x10\n\x08permlink\x18\x02 \x02(\t\x12<\n\nhbd_payout\x18\x03 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\nhbd_payout\x12>\n\x0bhive_payout\x18\x04 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x0bhive_payout\x12\x44\n\x0evesting_payout\x18\x05 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x0evesting_payout\x12V\n\x17\x63urators_vesting_payout\x18\x06 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x17\x63urators_vesting_payout\x12\x36\n\x16payout_must_be_claimed\x18\x07 \x02(\x08R\x16payout_must_be_claimed')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'author_reward_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUTHOR_REWARD']._serialized_start=60
  _globals['_AUTHOR_REWARD']._serialized_end=449
# @@protoc_insertion_point(module_scope)
