# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cancel_transfer_from_savings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"cancel_transfer_from_savings.proto\x12\x15hive.protocol.buffers\"Z\n\x1c\x63\x61ncel_transfer_from_savings\x12\x1a\n\x0c\x66rom_account\x18\x01 \x02(\tR\x04\x66rom\x12\x1e\n\nrequest_id\x18\x02 \x02(\rR\nrequest_id')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cancel_transfer_from_savings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CANCEL_TRANSFER_FROM_SAVINGS']._serialized_start=61
  _globals['_CANCEL_TRANSFER_FROM_SAVINGS']._serialized_end=151
# @@protoc_insertion_point(module_scope)
