# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fill_convert_request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x66ill_convert_request.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto\"\xb2\x01\n\x14\x66ill_convert_request\x12\r\n\x05owner\x18\x01 \x02(\t\x12\x11\n\trequestid\x18\x02 \x02(\r\x12:\n\tamount_in\x18\x03 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\tamount_in\x12<\n\namount_out\x18\x04 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\namount_out')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fill_convert_request_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILL_CONVERT_REQUEST']._serialized_start=67
  _globals['_FILL_CONVERT_REQUEST']._serialized_end=245
# @@protoc_insertion_point(module_scope)
