"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import asset_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class hardfork_hive_restore(google.protobuf.message.Message):
    """Related to hardfork 24.
    Generated for every account that was excluded from HF23 airdrop but won appeal.
    Note: the late airdrop did not apply properly since HIVE that the accounts should receive did not account for
    HIVE from converted VESTS. [how was it resolved?]
    @see hardfork_hive
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    TREASURY_FIELD_NUMBER: builtins.int
    HBD_TRANSFERRED_FIELD_NUMBER: builtins.int
    HIVE_TRANSFERRED_FIELD_NUMBER: builtins.int
    account: builtins.str
    """ @param {string} account - account to receive late airdrop (receiver of funds)"""
    treasury: builtins.str
    """@param {string} treasury - treasury, source of late airdrop"""
    @property
    def hbd_transferred(self) -> asset_pb2.asset:
        """@param {asset} hbd_transferred - (HBD) part of airdrop (equals related hardfork_hive_operation.hbd_transferred)"""
    @property
    def hive_transferred(self) -> asset_pb2.asset:
        """@param {asset} hive_transferred - (HIVE) part of airdrop (equals related hardfork_hive_operation.hive_transferred)"""
    def __init__(
        self,
        *,
        account: builtins.str | None = ...,
        treasury: builtins.str | None = ...,
        hbd_transferred: asset_pb2.asset | None = ...,
        hive_transferred: asset_pb2.asset | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account", b"account", "hbd_transferred", b"hbd_transferred", "hive_transferred", b"hive_transferred", "treasury", b"treasury"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account", b"account", "hbd_transferred", b"hbd_transferred", "hive_transferred", b"hive_transferred", "treasury", b"treasury"]) -> None: ...

global___hardfork_hive_restore = hardfork_hive_restore
