# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: legacy_chain_properties.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlegacy_chain_properties.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto\"\xc9\x01\n\x17legacy_chain_properties\x12P\n\x14\x61\x63\x63ount_creation_fee\x18\x01 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x14\x61\x63\x63ount_creation_fee\x12.\n\x12maximum_block_size\x18\x02 \x02(\rR\x12maximum_block_size\x12,\n\x11hbd_interest_rate\x18\x03 \x02(\rR\x11hbd_interest_rate')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'legacy_chain_properties_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LEGACY_CHAIN_PROPERTIES']._serialized_start=70
  _globals['_LEGACY_CHAIN_PROPERTIES']._serialized_end=271
# @@protoc_insertion_point(module_scope)
