"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import asset_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class pow_reward(google.protobuf.message.Message):
    """Related to pow_operation and pow2_operation.
    Generated every time one of above operations is executed (up to HF16).
    Note: pow2_operation could be executed up to HF17 but mining rewards were stopped after HF16.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORKER_FIELD_NUMBER: builtins.int
    REWARD_FIELD_NUMBER: builtins.int
    worker: builtins.str
    """@param {string} worker - (potentially new) witness that calculated PoW (receiver of reward)"""
    @property
    def reward(self) -> asset_pb2.asset:
        """@param {asset} reward - (VESTS or HIVE) reward for work (HIVE only during first 30 days after genesis)"""
    def __init__(
        self,
        *,
        worker: builtins.str | None = ...,
        reward: asset_pb2.asset | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["reward", b"reward", "worker", b"worker"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["reward", b"reward", "worker", b"worker"]) -> None: ...

global___pow_reward = pow_reward
