# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import future_extensions_pb2 as future__extensions__pb2
import transaction_pb2 as transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62lock.proto\x12\x15hive.protocol.buffers\x1a\x17\x66uture_extensions.proto\x1a\x11transaction.proto\"Q\n\x15hardfork_version_vote\x12\x1e\n\nhf_version\x18\x01 \x02(\tR\nhf_version\x12\x18\n\x07hf_time\x18\x02 \x02(\tR\x07hf_time\"\xd8\x01\n\x17\x62lock_header_extensions\x12\x37\n\x06void_t\x18\x01 \x01(\x0b\x32\x1d.hive.protocol.buffers.void_tH\x00R\x06void_t\x12\x11\n\x07version\x18\x02 \x01(\tH\x00\x12\x64\n\x15hardfork_version_vote\x18\x03 \x01(\x0b\x32,.hive.protocol.buffers.hardfork_version_voteH\x00R\x15hardfork_version_voteB\x0b\n\textension\"\x8b\x03\n\x05\x62lock\x12\x10\n\x08previous\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\t\x12\x0f\n\x07witness\x18\x03 \x02(\t\x12\x38\n\x17transaction_merkle_root\x18\x04 \x02(\tR\x17transaction_merkle_root\x12\x42\n\nextensions\x18\x05 \x03(\x0b\x32..hive.protocol.buffers.block_header_extensions\x12,\n\x11witness_signature\x18\x06 \x02(\tR\x11witness_signature\x12\x38\n\x0ctransactions\x18\x07 \x03(\x0b\x32\".hive.protocol.buffers.transaction\x12\x1a\n\x08\x62lock_id\x18\x08 \x02(\tR\x08\x62lock_id\x12 \n\x0bsigning_key\x18\t \x02(\tR\x0bsigning_key\x12(\n\x0ftransaction_ids\x18\n \x03(\tR\x0ftransaction_ids')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'block_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HARDFORK_VERSION_VOTE']._serialized_start=82
  _globals['_HARDFORK_VERSION_VOTE']._serialized_end=163
  _globals['_BLOCK_HEADER_EXTENSIONS']._serialized_start=166
  _globals['_BLOCK_HEADER_EXTENSIONS']._serialized_end=382
  _globals['_BLOCK']._serialized_start=385
  _globals['_BLOCK']._serialized_end=780
# @@protoc_insertion_point(module_scope)
