"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class cancel_transfer_from_savings(google.protobuf.message.Message):
    """Funds withdrawals from the savings can be canceled at any time before it is executed.

    Description https://gitlab.syncad.com/hive/hive/-/blob/develop/doc/devs/operations/34_cancel_transfer_from_savings.md?ref_type=heads
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FROM_ACCOUNT_FIELD_NUMBER: builtins.int
    REQUEST_ID_FIELD_NUMBER: builtins.int
    from_account: builtins.str
    """@param {string} from_account"""
    request_id: builtins.int
    """@param {number} request_id"""
    def __init__(
        self,
        *,
        from_account: builtins.str | None = ...,
        request_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["from_account", b"from_account", "request_id", b"request_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["from_account", b"from_account", "request_id", b"request_id"]) -> None: ...

global___cancel_transfer_from_savings = cancel_transfer_from_savings
