# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: changed_recovery_account.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "changed_recovery_account.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1e\x63hanged_recovery_account.proto\x12\x15hive.protocol.buffers"\x93\x01\n\x18\x63hanged_recovery_account\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x02(\t\x12\x32\n\x14old_recovery_account\x18\x02 \x02(\tR\x14old_recovery_account\x12\x32\n\x14new_recovery_account\x18\x03 \x02(\tR\x14new_recovery_account'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "changed_recovery_account_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CHANGED_RECOVERY_ACCOUNT"]._serialized_start = 58
    _globals["_CHANGED_RECOVERY_ACCOUNT"]._serialized_end = 205
# @@protoc_insertion_point(module_scope)
