# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: claim_account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2
import future_extensions_pb2 as future__extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63laim_account.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto\x1a\x17\x66uture_extensions.proto\"\x89\x01\n\rclaim_account\x12\x0f\n\x07\x63reator\x18\x01 \x02(\t\x12)\n\x03\x66\x65\x65\x18\x02 \x02(\x0b\x32\x1c.hive.protocol.buffers.asset\x12<\n\nextensions\x18\x03 \x03(\x0b\x32(.hive.protocol.buffers.future_extensions')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'claim_account_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLAIM_ACCOUNT']._serialized_start=85
  _globals['_CLAIM_ACCOUNT']._serialized_end=222
# @@protoc_insertion_point(module_scope)
