"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import asset_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class clear_null_account_balance(google.protobuf.message.Message):
    """Related to block processing.
    Generated during block processing potentially every block, but only if nonzero assets were burned. Triggered by removal of all
    assets from 'null' account balances.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOTAL_CLEARED_FIELD_NUMBER: builtins.int
    @property
    def total_cleared(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[asset_pb2.asset]:
        """@param {asset} total_cleared - (HIVE, VESTS or HBD) nonzero assets burned on 'null' account"""
    def __init__(
        self,
        *,
        total_cleared: collections.abc.Iterable[asset_pb2.asset] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["total_cleared", b"total_cleared"]) -> None: ...

global___clear_null_account_balance = clear_null_account_balance
