"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class custom(google.protobuf.message.Message):
    """There are the following custom operations: custom_operation, custom_json_operation and custom_binary (currently is disabled).
    The operation: custom_operation provides a generic way to add higher level protocols on top of witness consensus operations.

    @param {string} required_auths
    @param {number} id
    @param {string} data
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUIRED_AUTHS_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    @property
    def required_auths(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    id: builtins.int
    data: builtins.str
    def __init__(
        self,
        *,
        required_auths: collections.abc.Iterable[builtins.str] | None = ...,
        id: builtins.int | None = ...,
        data: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data", b"data", "id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "id", b"id", "required_auths", b"required_auths"]) -> None: ...

global___custom = custom
