# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ustom.proto\x12\x15hive.protocol.buffers\"J\n\x06\x63ustom\x12&\n\x0erequired_auths\x18\x01 \x03(\tR\x0erequired_auths\x12\n\n\x02id\x18\x02 \x02(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x02(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CUSTOM']._serialized_start=39
  _globals['_CUSTOM']._serialized_end=113
# @@protoc_insertion_point(module_scope)
