"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class decline_voting_rights(google.protobuf.message.Message):
    """Using the operation decline_voting_rights_operation, a user may decide to decline
    their voting rights – for content, witnesses and proposals.
    Additionally, a user cannot set a proxy (operation account_witness_proxy_operation).
    The operation is done with a HIVE_OWNER_AUTH_RECOVERY_PERIOD day delay.
    After HIVE_OWNER_AUTH_RECOVERY_PERIOD days it is irreversible.
    During HIVE_OWNER_AUTH_RECOVERY_PERIOD days after creation, the operation may be canceled
    using the operation declive_voting_rights_operation with {decline = false}.

    Description https://gitlab.syncad.com/hive/hive/-/blob/develop/doc/devs/operations/36_decline_voting_rights.md?ref_type=heads
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    DECLINE_FIELD_NUMBER: builtins.int
    account: builtins.str
    """@param {string} account - Account name."""
    decline: builtins.bool
    """@param {bool} decline"""
    def __init__(
        self,
        *,
        account: builtins.str | None = ...,
        decline: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account", b"account", "decline", b"decline"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account", b"account", "decline", b"decline"]) -> None: ...

global___decline_voting_rights = decline_voting_rights
