"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import asset_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class dhf_funding(google.protobuf.message.Message):
    """Related to block processing.
    Generated during block processing every proposal maintenance period.
    Note: while the fund receives part of inflation every block, the amount is recorded aside and only when there are
    proposal payouts (when new funds matter), there is generation of this vop.

    @param {string} treasury - treasury account (receiver of additional_funds)
    @param {asset} additional_funds - (HBD) portion inflation accumulated since previous maintenance period
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TREASURY_FIELD_NUMBER: builtins.int
    ADDITIONAL_FUNDS_FIELD_NUMBER: builtins.int
    treasury: builtins.str
    @property
    def additional_funds(self) -> asset_pb2.asset: ...
    def __init__(
        self,
        *,
        treasury: builtins.str | None = ...,
        additional_funds: asset_pb2.asset | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["additional_funds", b"additional_funds", "treasury", b"treasury"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["additional_funds", b"additional_funds", "treasury", b"treasury"]) -> None: ...

global___dhf_funding = dhf_funding
