"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class escrow_dispute(google.protobuf.message.Message):
    """The operation  escrow_dispute_operation is used to raise the dispute. It may be used by { from } or { to } accounts.
    If there is a dispute, only {agent} may release the funds.

    Description https://gitlab.syncad.com/hive/hive/-/blob/develop/doc/devs/operations/28_escrow_dispute.md?ref_type=heads
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FROM_ACCOUNT_FIELD_NUMBER: builtins.int
    TO_ACCOUNT_FIELD_NUMBER: builtins.int
    AGENT_FIELD_NUMBER: builtins.int
    WHO_FIELD_NUMBER: builtins.int
    ESCROW_ID_FIELD_NUMBER: builtins.int
    from_account: builtins.str
    """@param {string} from_account - Account name."""
    to_account: builtins.str
    """@param {string} to_account - Account name."""
    agent: builtins.str
    """@param {string} agent - Account name."""
    who: builtins.str
    """@param {string} who - Account name. Either {to} or {agent}."""
    escrow_id: builtins.int
    """@param {number} escrow_id - Escrow identifier."""
    def __init__(
        self,
        *,
        from_account: builtins.str | None = ...,
        to_account: builtins.str | None = ...,
        agent: builtins.str | None = ...,
        who: builtins.str | None = ...,
        escrow_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["agent", b"agent", "escrow_id", b"escrow_id", "from_account", b"from_account", "to_account", b"to_account", "who", b"who"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["agent", b"agent", "escrow_id", b"escrow_id", "from_account", b"from_account", "to_account", b"to_account", "who", b"who"]) -> None: ...

global___escrow_dispute = escrow_dispute
