# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hardfork_hive.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13hardfork_hive.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto\"\x9a\x03\n\rhardfork_hive\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x02(\t\x12\x10\n\x08treasury\x18\x02 \x02(\t\x12\x38\n\x17other_affected_accounts\x18\x03 \x03(\tR\x17other_affected_accounts\x12\x46\n\x0fhbd_transferred\x18\x04 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x0fhbd_transferred\x12H\n\x10hive_transferred\x18\x05 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x10hive_transferred\x12\x46\n\x0fvests_converted\x18\x06 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x0fvests_converted\x12R\n\x15total_hive_from_vests\x18\x07 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x15total_hive_from_vests')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hardfork_hive_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HARDFORK_HIVE']._serialized_start=60
  _globals['_HARDFORK_HIVE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
