"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import asset_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class hardfork_hive(google.protobuf.message.Message):
    """Related to hardfork 23 (HIVE inception hardfork).
    Generated for every account that did not receive HIVE airdrop.

    @param {string} account - account excluded from airdrop (source of amounts for airdrop)
    @param {string} treasury - treasury that received airdrop instead of account (receiver of funds)
    @param {string} other_affected_accounts - delegatees that lost delegations from account - filled before pre notification
    @param {asset} hbd_transferred - (HBD) part of airdrop to treasury (sourced from various HBD balances on account)
    @param {asset} hive_transferred - (HIVE) part of airdrop to treasury (sourced from various HIVE balances on account)
    @param {asset} vests_converted - (VESTS) sum of all sources of VESTS on account
    @param {asset} total_hive_from_vests - (HIVE) part of airdrop to treasury (sourced from conversion of vests_converted)
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    TREASURY_FIELD_NUMBER: builtins.int
    OTHER_AFFECTED_ACCOUNTS_FIELD_NUMBER: builtins.int
    HBD_TRANSFERRED_FIELD_NUMBER: builtins.int
    HIVE_TRANSFERRED_FIELD_NUMBER: builtins.int
    VESTS_CONVERTED_FIELD_NUMBER: builtins.int
    TOTAL_HIVE_FROM_VESTS_FIELD_NUMBER: builtins.int
    account: builtins.str
    treasury: builtins.str
    @property
    def other_affected_accounts(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def hbd_transferred(self) -> asset_pb2.asset: ...
    @property
    def hive_transferred(self) -> asset_pb2.asset: ...
    @property
    def vests_converted(self) -> asset_pb2.asset: ...
    @property
    def total_hive_from_vests(self) -> asset_pb2.asset: ...
    def __init__(
        self,
        *,
        account: builtins.str | None = ...,
        treasury: builtins.str | None = ...,
        other_affected_accounts: collections.abc.Iterable[builtins.str] | None = ...,
        hbd_transferred: asset_pb2.asset | None = ...,
        hive_transferred: asset_pb2.asset | None = ...,
        vests_converted: asset_pb2.asset | None = ...,
        total_hive_from_vests: asset_pb2.asset | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account", b"account", "hbd_transferred", b"hbd_transferred", "hive_transferred", b"hive_transferred", "total_hive_from_vests", b"total_hive_from_vests", "treasury", b"treasury", "vests_converted", b"vests_converted"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account", b"account", "hbd_transferred", b"hbd_transferred", "hive_transferred", b"hive_transferred", "other_affected_accounts", b"other_affected_accounts", "total_hive_from_vests", b"total_hive_from_vests", "treasury", b"treasury", "vests_converted", b"vests_converted"]) -> None: ...

global___hardfork_hive = hardfork_hive
