# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: limit_order_cancelled.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "limit_order_cancelled.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1blimit_order_cancelled.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto"x\n\x15limit_order_cancelled\x12\x0e\n\x06seller\x18\x01 \x02(\t\x12\x0f\n\x07orderid\x18\x02 \x02(\r\x12>\n\x0b\x61mount_back\x18\x03 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x0b\x61mount_back'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "limit_order_cancelled_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LIMIT_ORDER_CANCELLED"]._serialized_start = 67
    _globals["_LIMIT_ORDER_CANCELLED"]._serialized_end = 187
# @@protoc_insertion_point(module_scope)
