"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import future_extensions_pb2
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class recurrent_transfer_pair_id(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAIR_ID_FIELD_NUMBER: builtins.int
    pair_id: builtins.int
    def __init__(
        self,
        *,
        pair_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pair_id", b"pair_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["pair_id", b"pair_id"]) -> None: ...

global___recurrent_transfer_pair_id = recurrent_transfer_pair_id

@typing_extensions.final
class recurrent_transfer_extension(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VOID_T_FIELD_NUMBER: builtins.int
    RECURRENT_TRANSFER_PAIR_ID_FIELD_NUMBER: builtins.int
    @property
    def void_t(self) -> future_extensions_pb2.void_t: ...
    @property
    def recurrent_transfer_pair_id(self) -> global___recurrent_transfer_pair_id: ...
    def __init__(
        self,
        *,
        void_t: future_extensions_pb2.void_t | None = ...,
        recurrent_transfer_pair_id: global___recurrent_transfer_pair_id | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["recurrent_transfer_pair_id", b"recurrent_transfer_pair_id", "value", b"value", "void_t", b"void_t"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["recurrent_transfer_pair_id", b"recurrent_transfer_pair_id", "value", b"value", "void_t", b"void_t"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["value", b"value"]) -> typing_extensions.Literal["void_t", "recurrent_transfer_pair_id"] | None: ...

global___recurrent_transfer_extension = recurrent_transfer_extension
