# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recurrent_transfer_extension.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import future_extensions_pb2 as future__extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"recurrent_transfer_extension.proto\x12\x15hive.protocol.buffers\x1a\x17\x66uture_extensions.proto\"6\n\x1arecurrent_transfer_pair_id\x12\x18\n\x07pair_id\x18\x01 \x02(\rR\x07pair_id\"\xd5\x01\n\x1crecurrent_transfer_extension\x12\x37\n\x06void_t\x18\x01 \x01(\x0b\x32\x1d.hive.protocol.buffers.void_tH\x00R\x06void_t\x12s\n\x1arecurrent_transfer_pair_id\x18\x02 \x01(\x0b\x32\x31.hive.protocol.buffers.recurrent_transfer_pair_idH\x00R\x1arecurrent_transfer_pair_idB\x07\n\x05value')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recurrent_transfer_extension_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RECURRENT_TRANSFER_PAIR_ID']._serialized_start=86
  _globals['_RECURRENT_TRANSFER_PAIR_ID']._serialized_end=140
  _globals['_RECURRENT_TRANSFER_EXTENSION']._serialized_start=143
  _globals['_RECURRENT_TRANSFER_EXTENSION']._serialized_end=356
# @@protoc_insertion_point(module_scope)
