"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import asset_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class return_vesting_delegation(google.protobuf.message.Message):
    """Related to delegate_vesting_shares_operation.
    Generated during block processing when process of returning removed or lowered vesting delegation is finished (after return period
    passed) and delegator received back his vests.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    VESTING_SHARES_FIELD_NUMBER: builtins.int
    account: builtins.str
    """@param {string} account - delegator (receiver of vesting_shares)"""
    @property
    def vesting_shares(self) -> asset_pb2.asset:
        """@param {asset} vesting_shares - (VESTS) returned delegation"""
    def __init__(
        self,
        *,
        account: builtins.str | None = ...,
        vesting_shares: asset_pb2.asset | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account", b"account", "vesting_shares", b"vesting_shares"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account", b"account", "vesting_shares", b"vesting_shares"]) -> None: ...

global___return_vesting_delegation = return_vesting_delegation
