"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import asset_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class vesting_shares_split(google.protobuf.message.Message):
    """Related to hardfork 1.
    Generated for every account with nonzero vesting balance.
    Note: due to too small precision of VESTS asset it was increased by 6 digits, meaning all underlying
    amounts had to be multiplied by million.

    @param {string} owner - affected account (source of vesting_shares_before_split and receiver of vesting_shares_after_split)
    @param {asset} vesting_shares_before_split - (VESTS) balance before split
    @param {asset} vesting_shares_after_split - (VESTS) balance after split
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OWNER_FIELD_NUMBER: builtins.int
    VESTING_SHARES_BEFORE_SPLIT_FIELD_NUMBER: builtins.int
    VESTING_SHARES_AFTER_SPLIT_FIELD_NUMBER: builtins.int
    owner: builtins.str
    @property
    def vesting_shares_before_split(self) -> asset_pb2.asset: ...
    @property
    def vesting_shares_after_split(self) -> asset_pb2.asset: ...
    def __init__(
        self,
        *,
        owner: builtins.str | None = ...,
        vesting_shares_before_split: asset_pb2.asset | None = ...,
        vesting_shares_after_split: asset_pb2.asset | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["owner", b"owner", "vesting_shares_after_split", b"vesting_shares_after_split", "vesting_shares_before_split", b"vesting_shares_before_split"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["owner", b"owner", "vesting_shares_after_split", b"vesting_shares_after_split", "vesting_shares_before_split", b"vesting_shares_before_split"]) -> None: ...

global___vesting_shares_split = vesting_shares_split
