"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import asset_pb2
import authority_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class account_create(google.protobuf.message.Message):
    """A new account may be created only by an existing account.
    The account that creates a new account pays a fee.
    The fee amount is set by the witnesses.

    @param {asset} fee - Paid by creator. The witnesses decide the amount of the fee. Now, it is 3 HIVE.
    @param {string} creator - An account that creates a new account.
    @param {string} new_account_name - Valid account name may consist of many parts separated by a dot,
                                       total may have up to 16 characters, parts have to start from a letter,
                                       may be followed by numbers, or '-'.
    @param {authority} owner
    @param {authority} active
    @param {authority} posting
    @param {string} memo_key - Not authority, public memo key.
    @param {string} json_metadata
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEE_FIELD_NUMBER: builtins.int
    CREATOR_FIELD_NUMBER: builtins.int
    NEW_ACCOUNT_NAME_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    ACTIVE_FIELD_NUMBER: builtins.int
    POSTING_FIELD_NUMBER: builtins.int
    MEMO_KEY_FIELD_NUMBER: builtins.int
    JSON_METADATA_FIELD_NUMBER: builtins.int
    @property
    def fee(self) -> asset_pb2.asset: ...
    creator: builtins.str
    new_account_name: builtins.str
    @property
    def owner(self) -> authority_pb2.authority: ...
    @property
    def active(self) -> authority_pb2.authority: ...
    @property
    def posting(self) -> authority_pb2.authority: ...
    memo_key: builtins.str
    json_metadata: builtins.str
    def __init__(
        self,
        *,
        fee: asset_pb2.asset | None = ...,
        creator: builtins.str | None = ...,
        new_account_name: builtins.str | None = ...,
        owner: authority_pb2.authority | None = ...,
        active: authority_pb2.authority | None = ...,
        posting: authority_pb2.authority | None = ...,
        memo_key: builtins.str | None = ...,
        json_metadata: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["active", b"active", "creator", b"creator", "fee", b"fee", "json_metadata", b"json_metadata", "memo_key", b"memo_key", "new_account_name", b"new_account_name", "owner", b"owner", "posting", b"posting"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["active", b"active", "creator", b"creator", "fee", b"fee", "json_metadata", b"json_metadata", "memo_key", b"memo_key", "new_account_name", b"new_account_name", "owner", b"owner", "posting", b"posting"]) -> None: ...

global___account_create = account_create
