# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_created.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61\x63\x63ount_created.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto\"\xf2\x01\n\x0f\x61\x63\x63ount_created\x12*\n\x10new_account_name\x18\x01 \x02(\tR\x10new_account_name\x12\x0f\n\x07\x63reator\x18\x02 \x02(\t\x12T\n\x16initial_vesting_shares\x18\x03 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x16initial_vesting_shares\x12L\n\x12initial_delegation\x18\x04 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x12initial_delegation')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_created_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ACCOUNT_CREATED']._serialized_start=62
  _globals['_ACCOUNT_CREATED']._serialized_end=304
# @@protoc_insertion_point(module_scope)
