# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_witness_vote.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61\x63\x63ount_witness_vote.proto\x12\x15hive.protocol.buffers\"I\n\x14\x61\x63\x63ount_witness_vote\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x02(\t\x12\x0f\n\x07witness\x18\x02 \x02(\t\x12\x0f\n\x07\x61pprove\x18\x03 \x02(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_witness_vote_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACCOUNT_WITNESS_VOTE']._serialized_start=53
  _globals['_ACCOUNT_WITNESS_VOTE']._serialized_end=126
# @@protoc_insertion_point(module_scope)
