# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authority.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61uthority.proto\x12\x15hive.protocol.buffers\"\xc5\x02\n\tauthority\x12*\n\x10weight_threshold\x18\x01 \x02(\rR\x10weight_threshold\x12X\n\raccount_auths\x18\x02 \x03(\x0b\x32\x32.hive.protocol.buffers.authority.AccountAuthsEntryR\raccount_auths\x12L\n\tkey_auths\x18\x03 \x03(\x0b\x32..hive.protocol.buffers.authority.KeyAuthsEntryR\tkey_auths\x1a\x33\n\x11\x41\x63\x63ountAuthsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a/\n\rKeyAuthsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authority_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _AUTHORITY_ACCOUNTAUTHSENTRY._options = None
  _AUTHORITY_ACCOUNTAUTHSENTRY._serialized_options = b'8\001'
  _AUTHORITY_KEYAUTHSENTRY._options = None
  _AUTHORITY_KEYAUTHSENTRY._serialized_options = b'8\001'
  _globals['_AUTHORITY']._serialized_start=43
  _globals['_AUTHORITY']._serialized_end=368
  _globals['_AUTHORITY_ACCOUNTAUTHSENTRY']._serialized_start=268
  _globals['_AUTHORITY_ACCOUNTAUTHSENTRY']._serialized_end=319
  _globals['_AUTHORITY_KEYAUTHSENTRY']._serialized_start=321
  _globals['_AUTHORITY_KEYAUTHSENTRY']._serialized_end=368
# @@protoc_insertion_point(module_scope)
