"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import asset_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class collateralized_convert_immediate_conversion(google.protobuf.message.Message):
    """Related to collateralized_convert_operation.
    Generated every time above operation is executed. Contains amount of HBD received right when the transfer actually happens.
    @see fill_collateralized_convert_request

    @param {string} owner - user that requested conversion (receiver of hbd_out)
    @param {number} requested - id of the conversion request
    @param {asset} hbd_out - (HBD) funds after conversion
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OWNER_FIELD_NUMBER: builtins.int
    REQUESTID_FIELD_NUMBER: builtins.int
    HBD_OUT_FIELD_NUMBER: builtins.int
    owner: builtins.str
    requestid: builtins.int
    @property
    def hbd_out(self) -> asset_pb2.asset: ...
    def __init__(
        self,
        *,
        owner: builtins.str | None = ...,
        requestid: builtins.int | None = ...,
        hbd_out: asset_pb2.asset | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["hbd_out", b"hbd_out", "owner", b"owner", "requestid", b"requestid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["hbd_out", b"hbd_out", "owner", b"owner", "requestid", b"requestid"]) -> None: ...

global___collateralized_convert_immediate_conversion = collateralized_convert_immediate_conversion
