"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class comment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_AUTHOR_FIELD_NUMBER: builtins.int
    PARENT_PERMLINK_FIELD_NUMBER: builtins.int
    AUTHOR_FIELD_NUMBER: builtins.int
    PERMLINK_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    JSON_METADATA_FIELD_NUMBER: builtins.int
    parent_author: builtins.str
    parent_permlink: builtins.str
    author: builtins.str
    permlink: builtins.str
    title: builtins.str
    body: builtins.str
    json_metadata: builtins.str
    def __init__(
        self,
        *,
        parent_author: builtins.str | None = ...,
        parent_permlink: builtins.str | None = ...,
        author: builtins.str | None = ...,
        permlink: builtins.str | None = ...,
        title: builtins.str | None = ...,
        body: builtins.str | None = ...,
        json_metadata: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["author", b"author", "body", b"body", "json_metadata", b"json_metadata", "parent_author", b"parent_author", "parent_permlink", b"parent_permlink", "permlink", b"permlink", "title", b"title"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["author", b"author", "body", b"body", "json_metadata", b"json_metadata", "parent_author", b"parent_author", "parent_permlink", b"parent_permlink", "permlink", b"permlink", "title", b"title"]) -> None: ...

global___comment = comment
