# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consolidate_treasury_balance.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"consolidate_treasury_balance.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto\"^\n\x1c\x63onsolidate_treasury_balance\x12>\n\x0btotal_moved\x18\x01 \x03(\x0b\x32\x1c.hive.protocol.buffers.assetR\x0btotal_moved')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'consolidate_treasury_balance_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CONSOLIDATE_TREASURY_BALANCE']._serialized_start=74
  _globals['_CONSOLIDATE_TREASURY_BALANCE']._serialized_end=168
# @@protoc_insertion_point(module_scope)
