# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_json.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ustom_json.proto\x12\x15hive.protocol.buffers\"\x87\x01\n\x0b\x63ustom_json\x12&\n\x0erequired_auths\x18\x01 \x03(\tR\x0erequired_auths\x12\x36\n\x16required_posting_auths\x18\x02 \x03(\tR\x16required_posting_auths\x12\n\n\x02id\x18\x03 \x02(\t\x12\x0c\n\x04json\x18\x04 \x02(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_json_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CUSTOM_JSON']._serialized_start=45
  _globals['_CUSTOM_JSON']._serialized_end=180
# @@protoc_insertion_point(module_scope)
