# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: declined_voting_rights.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x64\x65\x63lined_voting_rights.proto\x12\x15hive.protocol.buffers\")\n\x16\x64\x65\x63lined_voting_rights\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x02(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'declined_voting_rights_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DECLINED_VOTING_RIGHTS']._serialized_start=55
  _globals['_DECLINED_VOTING_RIGHTS']._serialized_end=96
# @@protoc_insertion_point(module_scope)
