# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dhf_conversion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64hf_conversion.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto\"\xae\x01\n\x0e\x64hf_conversion\x12\x10\n\x08treasury\x18\x01 \x02(\t\x12\x44\n\x0ehive_amount_in\x18\x02 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x0ehive_amount_in\x12\x44\n\x0ehbd_amount_out\x18\x03 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x0ehbd_amount_out')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dhf_conversion_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DHF_CONVERSION']._serialized_start=61
  _globals['_DHF_CONVERSION']._serialized_end=235
# @@protoc_insertion_point(module_scope)
