# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: effective_comment_vote.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65\x66\x66\x65\x63tive_comment_vote.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto\"\xde\x01\n\x16\x65\x66\x66\x65\x63tive_comment_vote\x12\r\n\x05voter\x18\x01 \x02(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x02(\t\x12\x10\n\x08permlink\x18\x03 \x02(\t\x12\x0e\n\x06weight\x18\x04 \x02(\x04\x12\x0f\n\x07rshares\x18\x05 \x02(\x03\x12,\n\x11total_vote_weight\x18\x06 \x02(\x04R\x11total_vote_weight\x12\x44\n\x0epending_payout\x18\x07 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x0epending_payout')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'effective_comment_vote_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EFFECTIVE_COMMENT_VOTE']._serialized_start=69
  _globals['_EFFECTIVE_COMMENT_VOTE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
