# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: escrow_release.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65scrow_release.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto\"\x8e\x02\n\x0e\x65scrow_release\x12\x1a\n\x0c\x66rom_account\x18\x01 \x02(\tR\x04\x66rom\x12\x16\n\nto_account\x18\x02 \x02(\tR\x02to\x12\r\n\x05\x61gent\x18\x03 \x02(\t\x12\x0b\n\x03who\x18\x04 \x02(\t\x12\x10\n\x08receiver\x18\x05 \x02(\t\x12\x1c\n\tescrow_id\x18\x06 \x02(\rR\tescrow_id\x12<\n\nhbd_amount\x18\x07 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\nhbd_amount\x12>\n\x0bhive_amount\x18\x08 \x02(\x0b\x32\x1c.hive.protocol.buffers.assetR\x0bhive_amount')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'escrow_release_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ESCROW_RELEASE']._serialized_start=61
  _globals['_ESCROW_RELEASE']._serialized_end=331
# @@protoc_insertion_point(module_scope)
