# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: failed_recurrent_transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x66\x61iled_recurrent_transfer.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto\"\x84\x02\n\x19\x66\x61iled_recurrent_transfer\x12\x1a\n\x0c\x66rom_account\x18\x01 \x02(\tR\x04\x66rom\x12\x16\n\nto_account\x18\x02 \x02(\tR\x02to\x12,\n\x06\x61mount\x18\x03 \x02(\x0b\x32\x1c.hive.protocol.buffers.asset\x12\x0c\n\x04memo\x18\x04 \x02(\t\x12\x32\n\x14\x63onsecutive_failures\x18\x05 \x02(\rR\x14\x63onsecutive_failures\x12\x32\n\x14remaining_executions\x18\x06 \x02(\rR\x14remaining_executions\x12\x0f\n\x07\x64\x65leted\x18\x07 \x02(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'failed_recurrent_transfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FAILED_RECURRENT_TRANSFER']._serialized_start=72
  _globals['_FAILED_RECURRENT_TRANSFER']._serialized_end=332
# @@protoc_insertion_point(module_scope)
