# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: future_extensions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66uture_extensions.proto\x12\x15hive.protocol.buffers\"\x08\n\x06void_t\"Q\n\x11\x66uture_extensions\x12/\n\x06void_t\x18\x01 \x01(\x0b\x32\x1d.hive.protocol.buffers.void_tH\x00\x42\x0b\n\textension')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'future_extensions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VOID_T']._serialized_start=50
  _globals['_VOID_T']._serialized_end=58
  _globals['_FUTURE_EXTENSIONS']._serialized_start=60
  _globals['_FUTURE_EXTENSIONS']._serialized_end=141
# @@protoc_insertion_point(module_scope)
