# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ineffective_delete_comment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ineffective_delete_comment.proto\x12\x15hive.protocol.buffers\">\n\x1aineffective_delete_comment\x12\x0e\n\x06\x61uthor\x18\x01 \x02(\t\x12\x10\n\x08permlink\x18\x02 \x02(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ineffective_delete_comment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_INEFFECTIVE_DELETE_COMMENT']._serialized_start=59
  _globals['_INEFFECTIVE_DELETE_COMMENT']._serialized_end=121
# @@protoc_insertion_point(module_scope)
