# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0einterest.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto\"\x87\x01\n\x08interest\x12\r\n\x05owner\x18\x01 \x02(\t\x12.\n\x08interest\x18\x02 \x02(\x0b\x32\x1c.hive.protocol.buffers.asset\x12<\n\x19is_saved_into_hbd_balance\x18\x03 \x02(\x08R\x19is_saved_into_hbd_balance')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_INTEREST']._serialized_start=55
  _globals['_INTEREST']._serialized_end=190
# @@protoc_insertion_point(module_scope)
