# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: limit_order_cancel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18limit_order_cancel.proto\x12\x15hive.protocol.buffers\"4\n\x12limit_order_cancel\x12\r\n\x05order\x18\x08 \x02(\t\x12\x0f\n\x07orderid\x18\t \x02(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'limit_order_cancel_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LIMIT_ORDER_CANCEL']._serialized_start=51
  _globals['_LIMIT_ORDER_CANCEL']._serialized_end=103
# @@protoc_insertion_point(module_scope)
