# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: liquidity_reward.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import asset_pb2 as asset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16liquidity_reward.proto\x12\x15hive.protocol.buffers\x1a\x0b\x61sset.proto\"O\n\x10liquidity_reward\x12\r\n\x05owner\x18\x01 \x02(\t\x12,\n\x06payout\x18\x02 \x02(\x0b\x32\x1c.hive.protocol.buffers.asset')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'liquidity_reward_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LIQUIDITY_REWARD']._serialized_start=62
  _globals['_LIQUIDITY_REWARD']._serialized_end=141
# @@protoc_insertion_point(module_scope)
