"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import asset_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class proposal_pay(google.protobuf.message.Message):
    """Related to create_proposal_operation.
    Generated during block processing during proposal maintenance in batches
    for each proposal that is chosen and receives funding.

    @param {number} proposal_id - id of chosen proposal
    @param {string} receiver - account designated to receive funding (receiver of payment)
    @param {string} payer - treasury account, source of payment
    @param {asset} payment - (HBD) paid amount
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROPOSAL_ID_FIELD_NUMBER: builtins.int
    RECEIVER_FIELD_NUMBER: builtins.int
    PAYER_FIELD_NUMBER: builtins.int
    PAYMENT_FIELD_NUMBER: builtins.int
    proposal_id: builtins.int
    receiver: builtins.str
    payer: builtins.str
    @property
    def payment(self) -> asset_pb2.asset: ...
    def __init__(
        self,
        *,
        proposal_id: builtins.int | None = ...,
        receiver: builtins.str | None = ...,
        payer: builtins.str | None = ...,
        payment: asset_pb2.asset | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["payer", b"payer", "payment", b"payment", "proposal_id", b"proposal_id", "receiver", b"receiver"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["payer", b"payer", "payment", b"payment", "proposal_id", b"proposal_id", "receiver", b"receiver"]) -> None: ...

global___proposal_pay = proposal_pay
