# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reset_account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import authority_pb2 as authority__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13reset_account.proto\x12\x15hive.protocol.buffers\x1a\x0f\x61uthority.proto\"\xb5\x01\n\rreset_account\x12$\n\rreset_account\x18\x01 \x02(\tR\rreset_account\x12*\n\x10\x61\x63\x63ount_to_reset\x18\x02 \x02(\tR\x10\x61\x63\x63ount_to_reset\x12R\n\x13new_owner_authority\x18\x03 \x02(\x0b\x32 .hive.protocol.buffers.authorityR\x13new_owner_authority')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reset_account_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RESET_ACCOUNT']._serialized_start=64
  _globals['_RESET_ACCOUNT']._serialized_end=245
# @@protoc_insertion_point(module_scope)
