"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class set_reset_account(google.protobuf.message.Message):
    """This operation allows 'account' owner to control which account has the power
    to execute the 'reset_account_operation' after 60 days.

    @param {string} account
    @param {string} current_reset_account
    @param {string} reset_account
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    CURRENT_RESET_ACCOUNT_FIELD_NUMBER: builtins.int
    RESET_ACCOUNT_FIELD_NUMBER: builtins.int
    account: builtins.str
    current_reset_account: builtins.str
    reset_account: builtins.str
    def __init__(
        self,
        *,
        account: builtins.str | None = ...,
        current_reset_account: builtins.str | None = ...,
        reset_account: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account", b"account", "current_reset_account", b"current_reset_account", "reset_account", b"reset_account"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account", b"account", "current_reset_account", b"current_reset_account", "reset_account", b"reset_account"]) -> None: ...

global___set_reset_account = set_reset_account
