"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import account_create_pb2
import builtins
import collections.abc
import comment_pb2
import future_extensions_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import limit_order_cancel_pb2
import recurrent_transfer_pb2
import sys
import transfer_pb2
import vote_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class operation(google.protobuf.message.Message):
    """NOTE: do not change the order of any operations prior to the virtual operations
    or it will trigger a hardfork.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VOTE_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    TRANSFER_FIELD_NUMBER: builtins.int
    LIMIT_ORDER_CANCEL_FIELD_NUMBER: builtins.int
    ACCOUNT_CREATE_FIELD_NUMBER: builtins.int
    RECURRENT_TRANSFER_FIELD_NUMBER: builtins.int
    @property
    def vote(self) -> vote_pb2.vote: ...
    @property
    def comment(self) -> comment_pb2.comment: ...
    @property
    def transfer(self) -> transfer_pb2.transfer: ...
    @property
    def limit_order_cancel(self) -> limit_order_cancel_pb2.limit_order_cancel: ...
    @property
    def account_create(self) -> account_create_pb2.account_create: ...
    @property
    def recurrent_transfer(self) -> recurrent_transfer_pb2.recurrent_transfer: ...
    def __init__(
        self,
        *,
        vote: vote_pb2.vote | None = ...,
        comment: comment_pb2.comment | None = ...,
        transfer: transfer_pb2.transfer | None = ...,
        limit_order_cancel: limit_order_cancel_pb2.limit_order_cancel | None = ...,
        account_create: account_create_pb2.account_create | None = ...,
        recurrent_transfer: recurrent_transfer_pb2.recurrent_transfer | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_create", b"account_create", "comment", b"comment", "limit_order_cancel", b"limit_order_cancel", "recurrent_transfer", b"recurrent_transfer", "transfer", b"transfer", "value", b"value", "vote", b"vote"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_create", b"account_create", "comment", b"comment", "limit_order_cancel", b"limit_order_cancel", "recurrent_transfer", b"recurrent_transfer", "transfer", b"transfer", "value", b"value", "vote", b"vote"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["value", b"value"]) -> typing_extensions.Literal["vote", "comment", "transfer", "limit_order_cancel", "account_create", "recurrent_transfer"] | None: ...

global___operation = operation

@typing_extensions.final
class transaction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REF_BLOCK_NUM_FIELD_NUMBER: builtins.int
    REF_BLOCK_PREFIX_FIELD_NUMBER: builtins.int
    EXPIRATION_FIELD_NUMBER: builtins.int
    OPERATIONS_FIELD_NUMBER: builtins.int
    EXTENSIONS_FIELD_NUMBER: builtins.int
    ref_block_num: builtins.int
    ref_block_prefix: builtins.int
    expiration: builtins.str
    @property
    def operations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___operation]: ...
    @property
    def extensions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[future_extensions_pb2.future_extensions]: ...
    def __init__(
        self,
        *,
        ref_block_num: builtins.int | None = ...,
        ref_block_prefix: builtins.int | None = ...,
        expiration: builtins.str | None = ...,
        operations: collections.abc.Iterable[global___operation] | None = ...,
        extensions: collections.abc.Iterable[future_extensions_pb2.future_extensions] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["expiration", b"expiration", "ref_block_num", b"ref_block_num", "ref_block_prefix", b"ref_block_prefix"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["expiration", b"expiration", "extensions", b"extensions", "operations", b"operations", "ref_block_num", b"ref_block_num", "ref_block_prefix", b"ref_block_prefix"]) -> None: ...

global___transaction = transaction
