"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import account_create_pb2
import account_update2_pb2
import account_update_pb2
import account_witness_proxy_pb2
import account_witness_vote_pb2
import builtins
import cancel_transfer_from_savings_pb2
import change_recovery_account_pb2
import claim_account_pb2
import claim_reward_balance_pb2
import collateralized_convert_pb2
import collections.abc
import comment_options_pb2
import comment_pb2
import convert_pb2
import create_claimed_account_pb2
import create_proposal_pb2
import custom_json_pb2
import custom_pb2
import decline_voting_rights_pb2
import delegate_vesting_shares_pb2
import delete_comment_pb2
import escrow_approve_pb2
import escrow_dispute_pb2
import escrow_release_pb2
import escrow_transfer_pb2
import feed_publish_pb2
import future_extensions_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import limit_order_cancel_pb2
import limit_order_create2_pb2
import limit_order_create_pb2
import recover_account_pb2
import recurrent_transfer_pb2
import remove_proposal_pb2
import request_account_recovery_pb2
import set_withdraw_vesting_route_pb2
import sys
import transfer_from_savings_pb2
import transfer_pb2
import transfer_to_savings_pb2
import transfer_to_vesting_pb2
import update_proposal_pb2
import update_proposal_votes_pb2
import vote_pb2
import withdraw_vesting_pb2
import witness_block_approve_pb2
import witness_set_properties_pb2
import witness_update_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class operation(google.protobuf.message.Message):
    """NOTE: do not change the order of any operations prior to the virtual operations
    or it will trigger a hardfork.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VOTE_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    TRANSFER_FIELD_NUMBER: builtins.int
    TRANSFER_TO_VESTING_FIELD_NUMBER: builtins.int
    WITHDRAW_VESTING_FIELD_NUMBER: builtins.int
    LIMIT_ORDER_CREATE_FIELD_NUMBER: builtins.int
    LIMIT_ORDER_CANCEL_FIELD_NUMBER: builtins.int
    FEED_PUBLISH_FIELD_NUMBER: builtins.int
    CONVERT_FIELD_NUMBER: builtins.int
    ACCOUNT_CREATE_FIELD_NUMBER: builtins.int
    ACCOUNT_UPDATE_FIELD_NUMBER: builtins.int
    WITNESS_UPDATE_FIELD_NUMBER: builtins.int
    ACCOUNT_WITNESS_VOTE_FIELD_NUMBER: builtins.int
    ACCOUNT_WITNESS_PROXY_FIELD_NUMBER: builtins.int
    CUSTOM_FIELD_NUMBER: builtins.int
    WITNESS_BLOCK_APPROVE_FIELD_NUMBER: builtins.int
    DELETE_COMMENT_FIELD_NUMBER: builtins.int
    CUSTOM_JSON_FIELD_NUMBER: builtins.int
    COMMENT_OPTIONS_FIELD_NUMBER: builtins.int
    SET_WITHDRAW_VESTING_ROUTE_FIELD_NUMBER: builtins.int
    LIMIT_ORDER_CREATE2_FIELD_NUMBER: builtins.int
    CLAIM_ACCOUNT_FIELD_NUMBER: builtins.int
    CREATE_CLAIMED_ACCOUNT_FIELD_NUMBER: builtins.int
    REQUEST_ACCOUNT_RECOVERY_FIELD_NUMBER: builtins.int
    RECOVER_ACCOUNT_FIELD_NUMBER: builtins.int
    CHANGE_RECOVERY_ACCOUNT_FIELD_NUMBER: builtins.int
    ESCROW_TRANSFER_FIELD_NUMBER: builtins.int
    ESCROW_DISPUTE_FIELD_NUMBER: builtins.int
    ESCROW_RELEASE_FIELD_NUMBER: builtins.int
    ESCROW_APPROVE_FIELD_NUMBER: builtins.int
    TRANSFER_TO_SAVINGS_FIELD_NUMBER: builtins.int
    TRANSFER_FROM_SAVINGS_FIELD_NUMBER: builtins.int
    CANCEL_TRANSFER_FROM_SAVINGS_FIELD_NUMBER: builtins.int
    DECLINE_VOTING_RIGHTS_FIELD_NUMBER: builtins.int
    CLAIM_REWARD_BALANCE_FIELD_NUMBER: builtins.int
    DELEGATE_VESTING_SHARES_FIELD_NUMBER: builtins.int
    WITNESS_SET_PROPERTIES_FIELD_NUMBER: builtins.int
    ACCOUNT_UPDATE2_FIELD_NUMBER: builtins.int
    CREATE_PROPOSAL_FIELD_NUMBER: builtins.int
    UPDATE_PROPOSAL_VOTES_FIELD_NUMBER: builtins.int
    REMOVE_PROPOSAL_FIELD_NUMBER: builtins.int
    UPDATE_PROPOSAL_FIELD_NUMBER: builtins.int
    COLLATERALIZED_CONVERT_FIELD_NUMBER: builtins.int
    RECURRENT_TRANSFER_FIELD_NUMBER: builtins.int
    @property
    def vote(self) -> vote_pb2.vote: ...
    @property
    def comment(self) -> comment_pb2.comment: ...
    @property
    def transfer(self) -> transfer_pb2.transfer: ...
    @property
    def transfer_to_vesting(self) -> transfer_to_vesting_pb2.transfer_to_vesting: ...
    @property
    def withdraw_vesting(self) -> withdraw_vesting_pb2.withdraw_vesting: ...
    @property
    def limit_order_create(self) -> limit_order_create_pb2.limit_order_create: ...
    @property
    def limit_order_cancel(self) -> limit_order_cancel_pb2.limit_order_cancel: ...
    @property
    def feed_publish(self) -> feed_publish_pb2.feed_publish: ...
    @property
    def convert(self) -> convert_pb2.convert: ...
    @property
    def account_create(self) -> account_create_pb2.account_create: ...
    @property
    def account_update(self) -> account_update_pb2.account_update: ...
    @property
    def witness_update(self) -> witness_update_pb2.witness_update: ...
    @property
    def account_witness_vote(self) -> account_witness_vote_pb2.account_witness_vote: ...
    @property
    def account_witness_proxy(self) -> account_witness_proxy_pb2.account_witness_proxy: ...
    @property
    def custom(self) -> custom_pb2.custom: ...
    @property
    def witness_block_approve(self) -> witness_block_approve_pb2.witness_block_approve: ...
    @property
    def delete_comment(self) -> delete_comment_pb2.delete_comment: ...
    @property
    def custom_json(self) -> custom_json_pb2.custom_json: ...
    @property
    def comment_options(self) -> comment_options_pb2.comment_options: ...
    @property
    def set_withdraw_vesting_route(self) -> set_withdraw_vesting_route_pb2.set_withdraw_vesting_route: ...
    @property
    def limit_order_create2(self) -> limit_order_create2_pb2.limit_order_create2: ...
    @property
    def claim_account(self) -> claim_account_pb2.claim_account: ...
    @property
    def create_claimed_account(self) -> create_claimed_account_pb2.create_claimed_account: ...
    @property
    def request_account_recovery(self) -> request_account_recovery_pb2.request_account_recovery: ...
    @property
    def recover_account(self) -> recover_account_pb2.recover_account: ...
    @property
    def change_recovery_account(self) -> change_recovery_account_pb2.change_recovery_account: ...
    @property
    def escrow_transfer(self) -> escrow_transfer_pb2.escrow_transfer: ...
    @property
    def escrow_dispute(self) -> escrow_dispute_pb2.escrow_dispute: ...
    @property
    def escrow_release(self) -> escrow_release_pb2.escrow_release: ...
    @property
    def escrow_approve(self) -> escrow_approve_pb2.escrow_approve: ...
    @property
    def transfer_to_savings(self) -> transfer_to_savings_pb2.transfer_to_savings: ...
    @property
    def transfer_from_savings(self) -> transfer_from_savings_pb2.transfer_from_savings: ...
    @property
    def cancel_transfer_from_savings(self) -> cancel_transfer_from_savings_pb2.cancel_transfer_from_savings: ...
    @property
    def decline_voting_rights(self) -> decline_voting_rights_pb2.decline_voting_rights: ...
    @property
    def claim_reward_balance(self) -> claim_reward_balance_pb2.claim_reward_balance: ...
    @property
    def delegate_vesting_shares(self) -> delegate_vesting_shares_pb2.delegate_vesting_shares: ...
    @property
    def witness_set_properties(self) -> witness_set_properties_pb2.witness_set_properties: ...
    @property
    def account_update2(self) -> account_update2_pb2.account_update2: ...
    @property
    def create_proposal(self) -> create_proposal_pb2.create_proposal: ...
    @property
    def update_proposal_votes(self) -> update_proposal_votes_pb2.update_proposal_votes: ...
    @property
    def remove_proposal(self) -> remove_proposal_pb2.remove_proposal: ...
    @property
    def update_proposal(self) -> update_proposal_pb2.update_proposal: ...
    @property
    def collateralized_convert(self) -> collateralized_convert_pb2.collateralized_convert: ...
    @property
    def recurrent_transfer(self) -> recurrent_transfer_pb2.recurrent_transfer: ...
    def __init__(
        self,
        *,
        vote: vote_pb2.vote | None = ...,
        comment: comment_pb2.comment | None = ...,
        transfer: transfer_pb2.transfer | None = ...,
        transfer_to_vesting: transfer_to_vesting_pb2.transfer_to_vesting | None = ...,
        withdraw_vesting: withdraw_vesting_pb2.withdraw_vesting | None = ...,
        limit_order_create: limit_order_create_pb2.limit_order_create | None = ...,
        limit_order_cancel: limit_order_cancel_pb2.limit_order_cancel | None = ...,
        feed_publish: feed_publish_pb2.feed_publish | None = ...,
        convert: convert_pb2.convert | None = ...,
        account_create: account_create_pb2.account_create | None = ...,
        account_update: account_update_pb2.account_update | None = ...,
        witness_update: witness_update_pb2.witness_update | None = ...,
        account_witness_vote: account_witness_vote_pb2.account_witness_vote | None = ...,
        account_witness_proxy: account_witness_proxy_pb2.account_witness_proxy | None = ...,
        custom: custom_pb2.custom | None = ...,
        witness_block_approve: witness_block_approve_pb2.witness_block_approve | None = ...,
        delete_comment: delete_comment_pb2.delete_comment | None = ...,
        custom_json: custom_json_pb2.custom_json | None = ...,
        comment_options: comment_options_pb2.comment_options | None = ...,
        set_withdraw_vesting_route: set_withdraw_vesting_route_pb2.set_withdraw_vesting_route | None = ...,
        limit_order_create2: limit_order_create2_pb2.limit_order_create2 | None = ...,
        claim_account: claim_account_pb2.claim_account | None = ...,
        create_claimed_account: create_claimed_account_pb2.create_claimed_account | None = ...,
        request_account_recovery: request_account_recovery_pb2.request_account_recovery | None = ...,
        recover_account: recover_account_pb2.recover_account | None = ...,
        change_recovery_account: change_recovery_account_pb2.change_recovery_account | None = ...,
        escrow_transfer: escrow_transfer_pb2.escrow_transfer | None = ...,
        escrow_dispute: escrow_dispute_pb2.escrow_dispute | None = ...,
        escrow_release: escrow_release_pb2.escrow_release | None = ...,
        escrow_approve: escrow_approve_pb2.escrow_approve | None = ...,
        transfer_to_savings: transfer_to_savings_pb2.transfer_to_savings | None = ...,
        transfer_from_savings: transfer_from_savings_pb2.transfer_from_savings | None = ...,
        cancel_transfer_from_savings: cancel_transfer_from_savings_pb2.cancel_transfer_from_savings | None = ...,
        decline_voting_rights: decline_voting_rights_pb2.decline_voting_rights | None = ...,
        claim_reward_balance: claim_reward_balance_pb2.claim_reward_balance | None = ...,
        delegate_vesting_shares: delegate_vesting_shares_pb2.delegate_vesting_shares | None = ...,
        witness_set_properties: witness_set_properties_pb2.witness_set_properties | None = ...,
        account_update2: account_update2_pb2.account_update2 | None = ...,
        create_proposal: create_proposal_pb2.create_proposal | None = ...,
        update_proposal_votes: update_proposal_votes_pb2.update_proposal_votes | None = ...,
        remove_proposal: remove_proposal_pb2.remove_proposal | None = ...,
        update_proposal: update_proposal_pb2.update_proposal | None = ...,
        collateralized_convert: collateralized_convert_pb2.collateralized_convert | None = ...,
        recurrent_transfer: recurrent_transfer_pb2.recurrent_transfer | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_create", b"account_create", "account_update", b"account_update", "account_update2", b"account_update2", "account_witness_proxy", b"account_witness_proxy", "account_witness_vote", b"account_witness_vote", "cancel_transfer_from_savings", b"cancel_transfer_from_savings", "change_recovery_account", b"change_recovery_account", "claim_account", b"claim_account", "claim_reward_balance", b"claim_reward_balance", "collateralized_convert", b"collateralized_convert", "comment", b"comment", "comment_options", b"comment_options", "convert", b"convert", "create_claimed_account", b"create_claimed_account", "create_proposal", b"create_proposal", "custom", b"custom", "custom_json", b"custom_json", "decline_voting_rights", b"decline_voting_rights", "delegate_vesting_shares", b"delegate_vesting_shares", "delete_comment", b"delete_comment", "escrow_approve", b"escrow_approve", "escrow_dispute", b"escrow_dispute", "escrow_release", b"escrow_release", "escrow_transfer", b"escrow_transfer", "feed_publish", b"feed_publish", "limit_order_cancel", b"limit_order_cancel", "limit_order_create", b"limit_order_create", "limit_order_create2", b"limit_order_create2", "recover_account", b"recover_account", "recurrent_transfer", b"recurrent_transfer", "remove_proposal", b"remove_proposal", "request_account_recovery", b"request_account_recovery", "set_withdraw_vesting_route", b"set_withdraw_vesting_route", "transfer", b"transfer", "transfer_from_savings", b"transfer_from_savings", "transfer_to_savings", b"transfer_to_savings", "transfer_to_vesting", b"transfer_to_vesting", "update_proposal", b"update_proposal", "update_proposal_votes", b"update_proposal_votes", "value", b"value", "vote", b"vote", "withdraw_vesting", b"withdraw_vesting", "witness_block_approve", b"witness_block_approve", "witness_set_properties", b"witness_set_properties", "witness_update", b"witness_update"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_create", b"account_create", "account_update", b"account_update", "account_update2", b"account_update2", "account_witness_proxy", b"account_witness_proxy", "account_witness_vote", b"account_witness_vote", "cancel_transfer_from_savings", b"cancel_transfer_from_savings", "change_recovery_account", b"change_recovery_account", "claim_account", b"claim_account", "claim_reward_balance", b"claim_reward_balance", "collateralized_convert", b"collateralized_convert", "comment", b"comment", "comment_options", b"comment_options", "convert", b"convert", "create_claimed_account", b"create_claimed_account", "create_proposal", b"create_proposal", "custom", b"custom", "custom_json", b"custom_json", "decline_voting_rights", b"decline_voting_rights", "delegate_vesting_shares", b"delegate_vesting_shares", "delete_comment", b"delete_comment", "escrow_approve", b"escrow_approve", "escrow_dispute", b"escrow_dispute", "escrow_release", b"escrow_release", "escrow_transfer", b"escrow_transfer", "feed_publish", b"feed_publish", "limit_order_cancel", b"limit_order_cancel", "limit_order_create", b"limit_order_create", "limit_order_create2", b"limit_order_create2", "recover_account", b"recover_account", "recurrent_transfer", b"recurrent_transfer", "remove_proposal", b"remove_proposal", "request_account_recovery", b"request_account_recovery", "set_withdraw_vesting_route", b"set_withdraw_vesting_route", "transfer", b"transfer", "transfer_from_savings", b"transfer_from_savings", "transfer_to_savings", b"transfer_to_savings", "transfer_to_vesting", b"transfer_to_vesting", "update_proposal", b"update_proposal", "update_proposal_votes", b"update_proposal_votes", "value", b"value", "vote", b"vote", "withdraw_vesting", b"withdraw_vesting", "witness_block_approve", b"witness_block_approve", "witness_set_properties", b"witness_set_properties", "witness_update", b"witness_update"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["value", b"value"]) -> typing_extensions.Literal["vote", "comment", "transfer", "transfer_to_vesting", "withdraw_vesting", "limit_order_create", "limit_order_cancel", "feed_publish", "convert", "account_create", "account_update", "witness_update", "account_witness_vote", "account_witness_proxy", "custom", "witness_block_approve", "delete_comment", "custom_json", "comment_options", "set_withdraw_vesting_route", "limit_order_create2", "claim_account", "create_claimed_account", "request_account_recovery", "recover_account", "change_recovery_account", "escrow_transfer", "escrow_dispute", "escrow_release", "escrow_approve", "transfer_to_savings", "transfer_from_savings", "cancel_transfer_from_savings", "decline_voting_rights", "claim_reward_balance", "delegate_vesting_shares", "witness_set_properties", "account_update2", "create_proposal", "update_proposal_votes", "remove_proposal", "update_proposal", "collateralized_convert", "recurrent_transfer"] | None: ...

global___operation = operation

@typing_extensions.final
class transaction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REF_BLOCK_NUM_FIELD_NUMBER: builtins.int
    REF_BLOCK_PREFIX_FIELD_NUMBER: builtins.int
    EXPIRATION_FIELD_NUMBER: builtins.int
    OPERATIONS_FIELD_NUMBER: builtins.int
    EXTENSIONS_FIELD_NUMBER: builtins.int
    ref_block_num: builtins.int
    ref_block_prefix: builtins.int
    expiration: builtins.str
    @property
    def operations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___operation]: ...
    @property
    def extensions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[future_extensions_pb2.future_extensions]: ...
    def __init__(
        self,
        *,
        ref_block_num: builtins.int | None = ...,
        ref_block_prefix: builtins.int | None = ...,
        expiration: builtins.str | None = ...,
        operations: collections.abc.Iterable[global___operation] | None = ...,
        extensions: collections.abc.Iterable[future_extensions_pb2.future_extensions] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["expiration", b"expiration", "ref_block_num", b"ref_block_num", "ref_block_prefix", b"ref_block_prefix"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["expiration", b"expiration", "extensions", b"extensions", "operations", b"operations", "ref_block_num", b"ref_block_num", "ref_block_prefix", b"ref_block_prefix"]) -> None: ...

global___transaction = transaction
