# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vote.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nvote.proto\x12\x15hive.protocol.buffers\"G\n\x04vote\x12\r\n\x05voter\x18\n \x02(\t\x12\x0e\n\x06\x61uthor\x18\x0b \x02(\t\x12\x10\n\x08permlink\x18\x0c \x02(\t\x12\x0e\n\x06weight\x18\r \x02(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vote_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VOTE']._serialized_start=37
  _globals['_VOTE']._serialized_end=108
# @@protoc_insertion_point(module_scope)
