# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: witness_set_properties.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import future_extensions_pb2 as future__extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cwitness_set_properties.proto\x12\x15hive.protocol.buffers\x1a\x17\x66uture_extensions.proto\"\xdc\x01\n\x16witness_set_properties\x12\r\n\x05owner\x18\x01 \x02(\t\x12G\n\x05props\x18\x02 \x03(\x0b\x32\x38.hive.protocol.buffers.witness_set_properties.PropsEntry\x12<\n\nextensions\x18\x03 \x03(\x0b\x32(.hive.protocol.buffers.future_extensions\x1a,\n\nPropsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'witness_set_properties_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WITNESS_SET_PROPERTIES_PROPSENTRY._options = None
  _WITNESS_SET_PROPERTIES_PROPSENTRY._serialized_options = b'8\001'
  _globals['_WITNESS_SET_PROPERTIES']._serialized_start=81
  _globals['_WITNESS_SET_PROPERTIES']._serialized_end=301
  _globals['_WITNESS_SET_PROPERTIES_PROPSENTRY']._serialized_start=257
  _globals['_WITNESS_SET_PROPERTIES_PROPSENTRY']._serialized_end=301
# @@protoc_insertion_point(module_scope)
