"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import asset_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class interest(google.protobuf.message.Message):
    """Related to any operation that modifies HBD liquid or savings balance (including block processing).
    Generated when operation modified HBD balance and account received interest payment.
    Interest is stored in related balance (liquid when liquid was modified, savings when savings was modified).
    Note: since HF25 interest is not calculated nor paid on liquid balance.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OWNER_FIELD_NUMBER: builtins.int
    INTEREST_FIELD_NUMBER: builtins.int
    IS_SAVED_INTO_HBD_BALANCE_FIELD_NUMBER: builtins.int
    owner: builtins.str
    """@param {string} owner - user that had his HBD balance modified (receiver of interest)"""
    @property
    def interest(self) -> asset_pb2.asset:
        """@param {asset} interest - (HBD) amount of interest paid"""
    is_saved_into_hbd_balance: builtins.bool
    """@param {bool} is_saved_into_hbd_balance - true when liquid balance was modified (not happening after HF25)"""
    def __init__(
        self,
        *,
        owner: builtins.str | None = ...,
        interest: asset_pb2.asset | None = ...,
        is_saved_into_hbd_balance: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["interest", b"interest", "is_saved_into_hbd_balance", b"is_saved_into_hbd_balance", "owner", b"owner"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["interest", b"interest", "is_saved_into_hbd_balance", b"is_saved_into_hbd_balance", "owner", b"owner"]) -> None: ...

global___interest = interest
