use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::PathBuf;

use walrus::{ExportItem, Module, ValType};

fn get_wasm_f() -> String {
    std::env::var("WASM_FILE")
        .expect("WASM_FILE environment variable not set")
}

fn main() {
    let f = get_wasm_f();

    println!("cargo:rerun-if-env-changed=WASM_FILE");
    println!("cargo:rerun-if-changed={f}");
    println!("cargo:rerun-if-changed=build.rs");

    let module = Module::from_file(&f)
        .unwrap_or_else(|e| panic!("failed to parse {f}: {e}"));

    let mut funcs: Vec<FuncBinding> = Vec::new();
    for export in module.exports.iter() {
        let ExportItem::Function(fid) = export.item else {
            continue;
        };
        let func = module.funcs.get(fid);
        let ty = module.types.get(func.ty());
        funcs.push(FuncBinding {
            export_name: export.name.clone(),
            rust_name: sanitize_ident(&export.name),
            params: ty.params().to_vec(),
            results: ty.results().to_vec(),
        });
    }
    funcs.sort_by(|a, b| a.rust_name.cmp(&b.rust_name));
    disambiguate(&mut funcs);

    let code = render(&funcs);
    let manifest_dir = env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let dest = PathBuf::from(manifest_dir)
        .join("src")
        .join("generated")
        .join("wasm_bindings.rs");
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent).expect("failed to create generated/ dir");
    }
    let unchanged = fs::read_to_string(&dest)
        .map(|prev| prev == code)
        .unwrap_or(false);
    if !unchanged {
        fs::write(&dest, code).expect("failed to write generated bindings");
    }
}

struct FuncBinding {
    export_name: String,
    rust_name: String,
    params: Vec<ValType>,
    results: Vec<ValType>,
}

fn render(funcs: &[FuncBinding]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by build.rs from example.wasm — do not edit by hand.\n\n");
    out.push_str("#[allow(non_snake_case, non_camel_case_types, dead_code)]\n");
    out.push_str("pub struct WasmExports {\n");
    for f in funcs {
        out.push_str(&format!(
            "    pub {field}: ::wasmtime::TypedFunc<{params}, {results}>,\n",
            field = field_name(&f.rust_name),
            params = params_tuple(&f.params),
            results = results_type(&f.results),
        ));
    }
    out.push_str("}\n\n");

    out.push_str("#[allow(non_snake_case, dead_code)]\n");
    out.push_str("impl WasmExports {\n");
    out.push_str(
        "    pub fn new<T>(\n\
         \x20       instance: &::wasmtime::Instance,\n\
         \x20       store: &mut ::wasmtime::Store<T>,\n\
         \x20   ) -> ::wasmtime::Result<Self> {\n\
         \x20       Ok(Self {\n",
    );
    for f in funcs {
        out.push_str(&format!(
            "            {field}: instance.get_typed_func(&mut *store, {name:?})?,\n",
            field = field_name(&f.rust_name),
            name = f.export_name,
        ));
    }
    out.push_str("        })\n    }\n\n");

    for f in funcs {
        let params_sig: Vec<String> = f
            .params
            .iter()
            .enumerate()
            .map(|(i, t)| format!("p{i}: {ty}", ty = val_type_to_rust(*t)))
            .collect();
        let params_pass: Vec<String> = (0..f.params.len()).map(|i| format!("p{i}")).collect();
        let params_tuple = if params_pass.is_empty() {
            "()".into()
        } else if params_pass.len() == 1 {
            format!("({},)", params_pass[0])
        } else {
            format!("({})", params_pass.join(", "))
        };

        out.push_str(&format!(
            "    pub fn {name}<T>(\n\
             \x20       &self,\n\
             \x20       store: &mut ::wasmtime::Store<T>,\n\
             {sig}\
             \x20   ) -> ::wasmtime::Result<{results}> {{\n\
             \x20       self.{field}.call(store, {pass})\n\
             \x20   }}\n\n",
            name = f.rust_name,
            sig = if params_sig.is_empty() {
                String::new()
            } else {
                format!("        {},\n", params_sig.join(",\n        "))
            },
            results = results_type(&f.results),
            field = field_name(&f.rust_name),
            pass = params_tuple,
        ));
    }
    out.push_str("}\n");
    out
}

fn field_name(rust_name: &str) -> String {
    format!("{}_fn", rust_name.trim_start_matches("r#"))
}

fn params_tuple(params: &[ValType]) -> String {
    match params {
        [] => "()".into(),
        [single] => format!("({},)", val_type_to_rust(*single)),
        many => format!(
            "({})",
            many.iter()
                .map(|t| val_type_to_rust(*t))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn results_type(results: &[ValType]) -> String {
    match results {
        [] => "()".into(),
        [single] => val_type_to_rust(*single).into(),
        many => format!(
            "({})",
            many.iter()
                .map(|t| val_type_to_rust(*t))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn val_type_to_rust(v: ValType) -> &'static str {
    match v {
        ValType::I32 => "i32",
        ValType::I64 => "i64",
        ValType::F32 => "f32",
        ValType::F64 => "f64",
        ValType::V128 => "::wasmtime::V128",
        other => panic!("unsupported wasm value type for codegen: {other:?}"),
    }
}

fn sanitize_ident(name: &str) -> String {
    let mut s = String::new();
    for (i, c) in name.chars().enumerate() {
        let allowed = c.is_ascii_alphanumeric() || c == '_';
        if i == 0 && c.is_ascii_digit() {
            s.push('_');
            s.push(c);
        } else if allowed {
            s.push(c);
        } else {
            s.push('_');
        }
    }
    if s.is_empty() {
        s.push('_');
    }
    if is_rust_keyword(&s) {
        format!("r#{s}")
    } else {
        s
    }
}

fn is_rust_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "try"
    )
}

fn disambiguate(funcs: &mut [FuncBinding]) {
    let mut seen: HashSet<String> = HashSet::new();
    for f in funcs.iter_mut() {
        if !seen.insert(f.rust_name.clone()) {
            let mut n = 2;
            loop {
                let candidate = format!("{}_{n}", f.rust_name);
                if seen.insert(candidate.clone()) {
                    f.rust_name = candidate;
                    break;
                }
                n += 1;
            }
        }
    }
}
