FROM python:3.12-slim

WORKDIR /workspace

ENV VENV_PATH=/python_venv
RUN python3 -m venv $VENV_PATH
ENV PATH="$VENV_PATH/bin:$PATH"

ENV PIP_EXTRA_INDEX_URL="https://gitlab.syncad.com/api/v4/projects/362/packages/pypi/simple \
                         https://gitlab.syncad.com/api/v4/projects/198/packages/pypi/simple \
                         https://gitlab.syncad.com/api/v4/projects/419/packages/pypi/simple \
                         https://gitlab.syncad.com/api/v4/projects/434/packages/pypi/simple"

RUN pip install --upgrade pip && pip install --no-cache-dir 'wax==0.3.10.dev785+aeb3abb8'

ENV PYTHONUNBUFFERED=1
