[package]
name = "wax"
version = "0.1.0"
edition = "2024"

[dependencies]
wax_core = { path = "../wax_core" }
cxx = "1.0"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
rust_decimal = { version = "1", default-features = false, features = ["std"] }
serde_json = "1"
thiserror = "2"
serde = "1.0.228"

[dev-dependencies]
beekeeper_rust = { path = "../crates/beekeeper/programs/beekeeper/beekeeper_rust" }
