//! The formatter rule set: match rules, the stored format functions and the
//! [`CustomFormatter`] extension trait consumed by
//! [`WaxFormatter::extend`](super::formatter::WaxFormatter::extend).

use std::any::{Any, TypeId};
use std::collections::HashMap;
use std::sync::Arc;

use serde::Serialize;
use serde::de::DeserializeOwned;
use serde_json::Value;

use super::formatter::FoundationHandle;
use super::options::WaxFormatterOptions;

/// Provides construction and rule registration for formatter extensions
/// consumed by [`WaxFormatter::extend`](super::formatter::WaxFormatter::extend)
/// — usually generated by the `#[hive_formatter]` attribute.
pub trait CustomFormatter {
    /// Builds the formatter with the shared foundation handle.
    fn create(wax: FoundationHandle) -> Self;

    /// Registers this formatter's rules.
    fn register(self: &Arc<Self>, registry: &mut FormatterRegistry);
}

/// Represents the mutable rule set a [`CustomFormatter`] registers into.
#[derive(Clone, Default)]
pub struct FormatterRegistry {
    pub(crate) matchers: HashMap<String, MatcherData>,
    pub(crate) instances: HashMap<TypeId, InstanceFn>,
}

/// Represents a single match rule: the property to match, an optional value
/// the property must equal and the defined-value requirement.
///
/// Mirrors `IWaxFormatterDecoratorOptions` from
/// `ts/wasm/lib/detailed/decorators/formatters.ts`.
#[derive(Debug, Clone)]
pub struct MatchRule {
    property: String,
    value: Option<Value>,
    require_defined: bool,
}

/// Represents the arguments a format function receives.
///
/// Mirrors `IFormatFunctionArguments` from
/// `ts/wasm/lib/detailed/formatters/types.ts`.
pub struct FormatContext<'a> {
    /// Formatter options.
    pub options: &'a WaxFormatterOptions,
    /// The pristine object containing the matched property.
    pub source: &'a Value,
    /// The same node in the working tree, with children already formatted
    /// by other rules.
    pub target: &'a Value,
}

/// A stored format function (the TS `TFormatFunction`), shared across
/// registry clones through the [`Arc`]. `None` means "leave the node
/// unchanged".
pub type FormatFn =
    Arc<dyn Fn(&FormatContext<'_>) -> Option<Value> + Send + Sync>;

/// A stored typed-root format function (see
/// [`FormatterRegistry::register_instance`]).
pub(crate) type InstanceFn =
    Arc<dyn Fn(&WaxFormatterOptions, &dyn Any) -> Option<Value> + Send + Sync>;

/// Represents the stored matcher state of one property key.
///
/// Mirrors `IMatchersData` from `ts/wasm/lib/detailed/formatters/waxify.ts`.
#[derive(Clone)]
pub(crate) struct MatcherData {
    /// Value-matched rules, checked by equality against the property value.
    /// A `Vec` because `serde_json::Value` is not hashable and the lists
    /// stay tiny.
    pub(crate) match_values: Vec<(Value, FormatFn)>,
    pub(crate) default_formatter: Option<FormatFn>,
    pub(crate) require_defined: bool,
}

impl FormatterRegistry {
    /// Registers `format` under the given match rule. The typed `source`
    /// parameter is deserialized from the matched node — a failed
    /// deserialization skips the rule. Returning `None` from `format`
    /// leaves the node unchanged.
    pub fn register<T, R, F>(&mut self, rule: MatchRule, format: F)
    where
        T: DeserializeOwned,
        R: Serialize,
        F: Fn(&FormatContext<'_>, T) -> Option<R> + Send + Sync + 'static,
    {
        let wrapped: FormatFn = Arc::new(move |ctx| {
            let source =
                serde_json::from_value::<T>(ctx.source.clone()).ok()?;
            let result = format(ctx, source)?;

            serde_json::to_value(result).ok()
        });

        self.insert(rule, wrapped);
    }

    /// Sugar for [`Self::register`] with a property-wide rule.
    pub fn on_property<T, R, F>(&mut self, property: &str, format: F)
    where
        T: DeserializeOwned,
        R: Serialize,
        F: Fn(&FormatContext<'_>, T) -> Option<R> + Send + Sync + 'static,
    {
        self.register(MatchRule::property(property), format);
    }

    /// Sugar for [`Self::register`] with a value-matched rule.
    pub fn on_property_value<T, R, F>(
        &mut self,
        property: &str,
        value: impl Into<Value>,
        format: F,
    ) where
        T: DeserializeOwned,
        R: Serialize,
        F: Fn(&FormatContext<'_>, T) -> Option<R> + Send + Sync + 'static,
    {
        self.register(MatchRule::property_value(property, value), format);
    }

    /// Registers `format` for typed root inputs of type `T`, checked by
    /// [`WaxFormatter::format`](super::formatter::WaxFormatter::format)
    /// before serialization.
    ///
    /// TS NOTE: the closest port of `matchInstanceOf` — after serde
    /// serialization no type identity is left in the tree, so instance
    /// matching only applies to the typed root input, not to nested nodes
    /// (see `formatters_diff.md`).
    pub fn register_instance<T, R, F>(&mut self, format: F)
    where
        T: Any,
        R: Serialize,
        F: Fn(&WaxFormatterOptions, &T) -> Option<R> + Send + Sync + 'static,
    {
        let wrapped: InstanceFn = Arc::new(move |options, value| {
            let value = value.downcast_ref::<T>()?;
            let result = format(options, value)?;

            serde_json::to_value(result).ok()
        });

        self.instances.insert(TypeId::of::<T>(), wrapped);
    }

    fn insert(&mut self, rule: MatchRule, format: FormatFn) {
        match rule.value {
            // A value-matched registration joins the property's matcher;
            // re-registering the same value replaces it (last wins).
            Some(value) => {
                let matched = self
                    .matchers
                    .entry(rule.property)
                    .or_insert_with(|| MatcherData {
                        match_values: Vec::new(),
                        default_formatter: None,
                        require_defined: rule.require_defined,
                    });

                let existing = matched
                    .match_values
                    .iter_mut()
                    .find(|(candidate, _)| *candidate == value);

                if let Some((_, entry)) = existing {
                    *entry = format;
                } else {
                    matched.match_values.push((value, format));
                }
            }
            // TS NOTE: a property-wide registration replaces the whole
            // matcher, dropping previously registered value matches —
            // mirroring `overrideFormatterForMatcher` in `waxify.ts`.
            None => {
                self.matchers.insert(
                    rule.property,
                    MatcherData {
                        match_values: Vec::new(),
                        default_formatter: Some(format),
                        require_defined: rule.require_defined,
                    },
                );
            }
        }
    }
}

impl MatchRule {
    /// Creates a property-wide rule: fires for any object carrying the
    /// property.
    pub fn property(name: impl Into<String>) -> Self {
        Self {
            property: name.into(),
            value: None,
            require_defined: false,
        }
    }

    /// Creates a value-matched rule: fires only when the property equals
    /// `value`.
    pub fn property_value(
        name: impl Into<String>,
        value: impl Into<Value>,
    ) -> Self {
        Self {
            property: name.into(),
            value: Some(value.into()),
            require_defined: false,
        }
    }

    /// Requires the matched property to hold a defined value.
    ///
    /// TS NOTE: `requireDefined` guards `undefined` property values, which
    /// JSON cannot express — `null` is the closest equivalent here.
    pub fn require_defined(mut self) -> Self {
        self.require_defined = true;
        self
    }
}
