from __future__ import annotations

from .wax_result import (
    python_encrypted_memo,
    python_json_asset,
    python_ref_block_data,
    python_required_authority_collection,
    python_private_key_data,
    python_brain_key_data,
    python_binary_data,
    python_witness_set_properties_data,
    python_authorities,
    python_price
)

def calculate_public_key(wif: bytes) -> bytes: ...
def generate_private_key() -> bytes: ...
def generate_password_based_private_key(account: str, role: str, password: str) -> python_private_key_data: ...
def convert_raw_private_key_to_wif(hex_data: str) -> bytes: ...
def convert_raw_public_key_to_wif(hex_data: str) -> bytes: ...
def suggest_brain_key() -> python_brain_key_data: ...
def get_hive_protocol_config(chain_id: bytes) -> dict[bytes, bytes]: ...
def get_public_key_from_signature(digest: bytes, signature: bytes) -> bytes: ...
def general_asset(asset_num: int, amount: int) -> python_json_asset: ...
def hive(amount: int) -> python_json_asset: ...
def hbd(amount: int) -> python_json_asset: ...
def vests(amount: int) -> python_json_asset: ...
def serialize_witness_set_properties(input_props: python_witness_set_properties_data) -> dict[bytes, bytes]: ...
def deserialize_witness_set_properties(serialized_properties: dict[bytes, bytes]) -> python_witness_set_properties_data: ...
def asset_value(value: python_json_asset) -> bytes: ...
def asset_symbol(value: python_json_asset) -> bytes: ...
def verify_exception_handling(throw_type: int) -> None: ...
def decode_encrypted_memo(encoded_memo: bytes) -> python_encrypted_memo: ...
def encode_encrypted_memo(encrypted_content: bytes, main_encryption_key: bytes, other_encryption_key: bytes = b'') -> bytes: ...
def check_memo_for_private_keys(memo: bytes, account: bytes, auths: python_authorities, memo_key: bytes, imported_keys: list[bytes]) -> None: ...
def calculate_manabar_full_regeneration_time(now: int, max_mana: int, current_mana: int, last_update_time: int) -> int: ...
def calculate_current_manabar_value(now: int, max_mana: int, current_mana: int, last_update_time: int) -> int: ...
def get_tapos_data(block_id: bytes) -> python_ref_block_data: ...
def calculate_hp_apr(
    head_block_num: int,
    vesting_reward_percent: int,
    virtual_supply: python_json_asset,
    total_vesting_fund_hive: python_json_asset
) -> bytes: ...
def calculate_hbd_to_hive(
    hbd: python_json_asset,
    base: python_json_asset,
    quote: python_json_asset
) -> python_json_asset: ...
def calculate_hive_to_hbd(
    amount: python_json_asset,
    base: python_json_asset,
    quote: python_json_asset
) -> python_json_asset: ...
def calculate_vests_to_hp(
    vests: python_json_asset,
    total_vesting_fund_hive: python_json_asset,
    total_vesting_shares: python_json_asset
) -> python_json_asset: ...
def calculate_hp_to_vests(
    hive: python_json_asset,
    total_vesting_fund_hive: python_json_asset,
    total_vesting_shares: python_json_asset
) -> python_json_asset: ...
def calculate_inflation_rate_for_block(block_num: int) -> int: ...
def estimate_hive_collateral(
    current_median_history: python_price,
    current_min_history: python_price,
    hbd_amount_to_get: python_json_asset
) -> python_json_asset: ...
def is_valid_account_name(account_name: bytes) -> bool: ...
def get_default_comment_options_operation() -> bytes: ...

class WaxTransactionHandle: ...
class WaxOperationHandle: ...

def deserialize_transaction(transaction_data: bytes) -> WaxTransactionHandle: ...
def deserialize_operation(operation_data: bytes) -> WaxOperationHandle: ...
def op_impacted_accounts(wax_op: WaxOperationHandle) -> list[str]: ...
def op_to_binary(wax_op: WaxOperationHandle, use_hf26_serialization: bool = True) -> bytes: ...
def op_binary(wax_op: WaxOperationHandle, use_hf26_serialization: bool = True) -> python_binary_data: ...
def op_validate(wax_op: WaxOperationHandle) -> None: ...
def op_required_authorities(wax_op: WaxOperationHandle) -> python_required_authority_collection: ...
def tx_add_operation(wax_tx: WaxTransactionHandle, wax_op: WaxOperationHandle) -> None: ...
def tx_add_signature(wax_tx: WaxTransactionHandle, signature: bytes) -> None: ...
def tx_set_expiration(wax_tx: WaxTransactionHandle, expiration: bytes) -> None: ...
def tx_to_legacy_json(wax_tx: WaxTransactionHandle) -> bytes: ...
def tx_to_binary(wax_tx: WaxTransactionHandle, use_hf26_serialization: bool = True, strip_to_unsigned_transaction: bool = False) -> bytes: ...
def tx_to_json(wax_tx: WaxTransactionHandle) -> bytes: ...
def tx_id(wax_tx: WaxTransactionHandle, use_hf26_serialization: bool = True) -> bytes: ...
def tx_binary(wax_tx: WaxTransactionHandle, use_hf26_serialization: bool = True, strip_to_unsigned_transaction: bool = False) -> python_binary_data: ...
def tx_required_authorities(wax_tx: WaxTransactionHandle) -> python_required_authority_collection: ...
def tx_impacted_accounts(wax_tx: WaxTransactionHandle) -> list[str]: ...
def tx_signature_keys(wax_tx: WaxTransactionHandle, chain_id: bytes, use_hf26_serialization: bool = True) -> list[str]: ...
def tx_sig_digest(wax_tx: WaxTransactionHandle, chain_id: bytes, use_hf26_serialization: bool = True) -> bytes: ...
def tx_validate(wax_tx: WaxTransactionHandle) -> None: ...
def tx_proto_to_api(tx: object) -> None: ...
def tx_api_to_proto(transaction: object) -> None: ...
def create_wax_transaction(tx: object, is_protobuf: bool) -> WaxTransactionHandle: ...
def create_wax_operation(op: object, is_protobuf: bool) -> WaxOperationHandle: ...
def calculate_account_hp(
    vests: python_json_asset,
    total_vesting_fund_hive: python_json_asset,
    total_vesting_shares: python_json_asset
) -> python_json_asset: ...
def calculate_witness_votes_hp(
    votes: int,
    total_vesting_fund_hive: python_json_asset,
    total_vesting_shares: python_json_asset
) -> python_json_asset: ...
