site_name: !ENV [WAX_PYDOC_SITE_NAME, 'Wax Python interface']
site_url: !ENV [WAX_PYDOC_SITE_URL, 'https://gitlab.syncad.com/']
repo_name: !ENV [WAX_PYDOC_REPO_NAME, 'hive/wax']
repo_url: !ENV [WAX_PYDOC_REPO_URL, 'https://gitlab.syncad.com/hive/wax/']

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 1

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.path
    - navigation.instant.progress
    - navigation.top
    - search.highlight
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            parameter_headings: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature_annotations: true
            show_submodules: true  # consider disabling (which is disabled by default) so we can manage the structure in a better way
            separate_signature: true
            signature_crossrefs: true
            merge_init_into_class: true

extra_css:
  - custom.css

nav:
  - Home: index.md
  - tutorial.md
  - How-To Guides: how-to-guides.md
  - reference.md
