files: |
    (?x)(
            ^python/wax/wax/.*$|
            ^python/test_tools/test_tools/.*$|
            ^python/wax/tests/base_api/.*$|
            ^python/wax/tests/chain_api/.*$|
            ^python/wax/tests/transactions/.*$|
            ^python/wax/tests/helpy_test/.*$|
            ^python/wax/tests/apps_operations/.*$|
            ^python/test_tools/tests/.*$
    )
exclude: |
    (?x)(
            ^python/wax/wax/cpp_python_bridge.pyi|
            ^python/wax/wax/_private/proto/.*$
    )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        args: [ "--unsafe" ]
      - id: check-json
      - id: pretty-format-json
        args: [ "--autofix" ]
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
      - id: poetry-lock
        name: checking if wax poetry.lock is consistent with pyproject.toml
        args: [ "-C", "./python/wax"]
        language_version: python3.12
      - id: poetry-lock
        name: checking if test-tools poetry.lock is consistent with pyproject.toml
        args: [ "-C", "./python/test_tools"]
        language_version: python3.12
      - id: poetry-lock
        name: checking if examples poetry.lock is consistent with pyproject.toml
        args: [ "-C", "./examples/python"]
        language_version: python3.12
  - repo: local
    hooks:
      - id: ruff
        name: linting code with Ruff
        entry: ruff check --force-exclude --fix
        language: system
        types: [python]
      - id: ruff-format
        name: format code using Ruff formatter
        entry: ruff format --force-exclude
        language: system
        types: [python]
      - id: mypy-wax
        name: type check wax with mypy
        entry: mypy
        args: ["--config-file", "python/wax/pyproject.toml", "python/wax/wax", "python/wax/tests/base_api", "python/wax/tests/chain_api", "python/wax/tests/transactions", "python/wax/tests/helpy_test", "python/wax/tests/apps_operations"]
        language: system
        types: [python]
        pass_filenames: false
      - id: mypy-test-tools
        name: type check test-tools with mypy
        entry: mypy
        args: ["--config-file", "python/test_tools/pyproject.toml", "python/test_tools/test_tools"]
        language: system
        types: [python]
        pass_filenames: false
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
    - id: codespell
  - repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
      - id: detect-missing-init
        args:
          - "--create"
          - "--python-folders"
          - "\
            python/wax/wax,
            python/test_tools/test_tools,
            "
