# -*- coding: utf-8 -*-

# tag: cpp17

from libcpp.string cimport string
from libcpp.pair cimport pair
from libcpp.vector cimport vector
from libcpp.set cimport set as cppset
from libcpp.map cimport map as cppmap
from libcpp.optional cimport optional as cpp_optional
from libc.stdint cimport uint16_t, uint32_t, int32_t
from libcpp cimport bool
from libcpp.memory cimport unique_ptr
from libcpp.optional cimport optional

cdef extern from "Python.h" nogil:
    ctypedef struct PyObject

cdef extern from *:
    """
    #include "core/exception.hpp"
    #include <Python.h>
    #include <stdexcept>
    #include <ios>

    PyObject *ChainAssertionErrorIndicator;
    PyObject *ProtocolAssertionErrorIndicator;
    PyObject *AssertionErrorIndicator;

    void create_custom_exceptions() {
        ChainAssertionErrorIndicator = PyErr_NewException("wax.ChainAssertionErrorIndicator", NULL, NULL);
        ProtocolAssertionErrorIndicator = PyErr_NewException("wax.ProtocolAssertionErrorIndicator", NULL, NULL);
        AssertionErrorIndicator = PyErr_NewException("wax.AssertionErrorIndicator", NULL, NULL);
    }

    void custom_exception_handler() {
        try {
            if (PyErr_Occurred()) {
                ; // let the latest Python exn pass through and ignore the current one
            } else {
                throw;
            }
        } catch (const cpp::wax_chain_assertion& exn) {
            PyErr_SetString(ChainAssertionErrorIndicator, exn.what());
        } catch (const cpp::wax_protocol_assertion& exn) {
            PyErr_SetString(ProtocolAssertionErrorIndicator, exn.what());
        } catch (const cpp::wax_assertion& exn) {
            PyErr_SetString(AssertionErrorIndicator, exn.what());
        } catch (const std::exception& exn) {
            PyErr_SetString(PyExc_RuntimeError, exn.what());
        } catch (...) {
            PyErr_SetString(PyExc_RuntimeError, "Unknown exception");
        }
    }
    """
    cdef PyObject* ChainAssertionErrorIndicator
    cdef PyObject* ProtocolAssertionErrorIndicator
    cdef PyObject* AssertionErrorIndicator
    cdef void create_custom_exceptions()
    cdef void custom_exception_handler()

cdef extern from "cpython_interface.hpp" namespace "cpp":
    cdef cppclass wax_tx_ptr_deleter:
        pass

    cdef cppclass wax_op_ptr_deleter:
        pass

    cdef cppclass hive_tx:
        pass

    cdef cppclass hive_op:
        pass

    cdef cppclass hive_transaction_handle:
        hive_transaction_handle() except +
        unique_ptr[hive_tx, wax_tx_ptr_deleter] tx

    cdef cppclass hive_operation_handle:
        hive_operation_handle() except +
        unique_ptr[hive_op, wax_op_ptr_deleter] op

    cdef enum error_code:
        fail = 0
        ok = 1

    cdef cppclass result:
        result() except +

        error_code value
        string content
        string exception_message

    cdef cppclass json_asset:
        json_asset() except +
        json_asset( string _amount, int _precision, string _nai ) except +

        string amount
        int precision
        string nai

    cdef cppclass json_price:
        json_price() except +

        json_asset base
        json_asset quote

    cdef cppclass ref_block_data:
        ref_block_data() noexcept

        uint16_t ref_block_num
        uint32_t ref_block_prefix

    cdef cppclass required_authority_collection:
         required_authority_collection() except +
         ctypedef vector[string] account_vector

         account_vector posting_accounts
         account_vector active_accounts
         account_vector owner_accounts
         vector[wax_authority] other_authorities

    cdef cppclass crypto_memo:
         crypto_memo() except +

         # base58 encoded public key, used for encryption (encryption is performed by matching private key)
         string _from

         # base58 encoded public key, used for encryption (additionally allows decryption by using matching private key)
         string to

         # base58 encoded encrypted content
         string content

    cdef cppclass private_key_data:
        private_key_data() except +

        string wif_private_key
        string associated_public_key

    cdef cppclass brain_key_data:
        brain_key_data() except +

        # String containing a space-separated list of N (atm 16) words generated by suggest_brain_key function
        string brain_key
        # First private key derived from brain key
        string wif_private_key
        # The public key associated to private key above (starts with HIVE_ADDRESS_PREFIX)
        string associated_public_key

    cpdef cppclass witness_set_properties_data:
        witness_set_properties_data() except +

        string key
        # New witness key to set
        cpp_optional[string] new_signing_key
        # HIVE maximum account creation fee
        cpp_optional[json_asset]  account_creation_fee
        # New witness URL to set
        cpp_optional[string] url
        # HBD to HIVE ratio proposed by the witness
        cpp_optional[json_price]       hbd_exchange_rate
        # This witnesses vote for the maximum_block_size which is used by the network to tune rate limiting and capacity
        cpp_optional[uint32_t]    maximum_block_size
        # Rate of interest for holding HBD (in BPS - basis points)
        cpp_optional[uint16_t]    hbd_interest_rate
        # How many free accounts should be created per elected witness block. Scaled so that HIVE_ACCOUNT_SUBSIDY_PRECISION represents one account.
        cpp_optional[int32_t]     account_subsidy_budget
        # What fraction of the "stockpiled" free accounts "expire" per elected witness block. Scaled so that 1 << HIVE_RD_DECAY_DENOM_SHIFT represents 100% of accounts expiring.
        cpp_optional[uint32_t]    account_subsidy_decay

    cdef cppclass wax_authority:
        wax_authority() except +

        ctypedef cppmap[string, uint16_t] authority_map

        uint32_t      weight_threshold
        authority_map account_auths
        authority_map key_auths

    cdef cppclass wax_authorities:
        wax_authorities() except +

        wax_authority active
        wax_authority owner
        wax_authority posting

    ctypedef cppmap[string, string] witness_set_properties_serialized
    ctypedef cppmap[string, wax_authorities] wax_authorities_map_t
    ctypedef wax_authorities_map_t (*retrieve_authorities_t)(vector[string], void* ) except +
    ctypedef string (*get_witness_key_t)(string, void* ) except +

    cdef cppclass minimize_required_signatures_data_t:
        minimize_required_signatures_data_t() except +

        string chain_id
        vector[string] available_keys
        wax_authorities_map_t authorities_map
        get_witness_key_t get_witness_key_cb
        void* get_witness_key_fn
        cpp_optional[uint32_t] max_recursion
        cpp_optional[uint32_t] max_membership
        cpp_optional[uint32_t] max_account_auths
        bool allow_strict_and_mixed_authorities

    cdef cppclass binary_data_node:
        string key
        string type
        uint32_t offset
        uint32_t size
        string value
        uint32_t length
        vector[binary_data_node] children

    cdef cppclass binary_data:
        string binary
        vector[binary_data_node] offsets

    cdef cppclass authority_trace_path_entry:
        string processed_entry
        string processed_role
        uint32_t recursion_depth
        uint32_t threshold
        uint32_t weight
        uint32_t flags
        vector[authority_trace_path_entry] visited_entries

    cdef cppclass authority_verification_trace:
        vector[authority_trace_path_entry] root
        vector[authority_trace_path_entry] final_authority_path
        uint32_t verification_status

    cdef cppclass IAccountAuthorityProvider:
        IAccountAuthorityProvider() except +
        optional[wax_authority] getAuthority(string account_name, string authorityRole) except +
        optional[string] getWitnessPublicKey(string witness_name) except +

    cdef cppclass protocol:
        string cpp_calculate_public_key(string wif) except +
        string cpp_generate_private_key() except +
        private_key_data cpp_generate_private_key(string account, string role, string password) except +

        string cpp_convert_raw_private_key_to_wif(string hexData) except +

        string cpp_convert_raw_public_key_to_wif(string hexData) except +

        brain_key_data cpp_suggest_brain_key() except +

        cppmap[string, string] cpp_get_hive_protocol_config(string chain_id) except +

        string cpp_get_public_key_from_signature(string digest, string signature) except +

        json_asset cpp_general_asset(long asset_num, long amount)except +
        json_asset cpp_hive(long amount)except +
        json_asset cpp_hbd(long amount)except +
        json_asset cpp_vests(long amount)except +

        witness_set_properties_serialized cpp_serialize_witness_set_properties(witness_set_properties_data value) except +
        witness_set_properties_data cpp_deserialize_witness_set_properties(witness_set_properties_serialized value) except +

        vector[string] cpp_collect_signing_keys( hive_transaction_handle tx_handle, retrieve_authorities_t retrieve_authorities, void* retrieve_authorities_fn ) except +
        vector[string] cpp_minimize_required_signatures( hive_transaction_handle tx_handle, minimize_required_signatures_data_t minimize_required_signatures_data ) except +

        string cpp_asset_value(json_asset value) except +
        string cpp_asset_symbol(json_asset value) except +

        void cpp_throws(int type) except +custom_exception_handler

        crypto_memo cpp_crypto_memo_from_string(string value) except +

        string cpp_crypto_memo_dump_string(crypto_memo value) except +

        void cpp_check_memo_for_private_keys(string memo, string account, wax_authorities auths, string memo_key, vector[string] imported_keys) except +

        long cpp_calculate_manabar_full_regeneration_time(int32_t now, long max_mana, long current_mana, uint32_t last_update_time) except +
        long cpp_calculate_current_manabar_value(int32_t now, long max_mana, long current_mana, uint32_t last_update_time) except +

        ref_block_data cpp_get_tapos_data(string block_id) except +

        string cpp_calculate_hp_apr(uint32_t head_block_num, uint16_t vesting_reward_percent, json_asset virtual_supply, json_asset total_vesting_fund_hive) except +

        json_asset cpp_hbd_to_hive(json_asset hbd, json_asset base, json_asset quote) except +

        json_asset cpp_hive_to_hbd(json_asset amount, json_asset base, json_asset quote) except +

        json_asset cpp_vests_to_hp(json_asset vests, json_asset total_vesting_fund_hive, json_asset total_vesting_shares) except +

        json_asset cpp_hp_to_vests(json_asset hive, json_asset total_vesting_fund_hive, json_asset total_vesting_shares) except +

        long cpp_calculate_inflation_rate_for_block(uint32_t block_num) except +

        json_asset cpp_estimate_hive_collateral( json_price current_median_history, json_price current_min_history, json_asset hbd_amount_to_get ) except +

        bool cpp_is_valid_account_name( string name ) except +

        authority_verification_trace cpp_trace_authority_verification(
            required_authority_collection required_authorities,
            vector[string] decodedSignaturePublicKeys,
            IAccountAuthorityProvider& authorityProvider) except +

        string cpp_get_default_comment_options_operation() except +

        hive_transaction_handle cpp_deserialize_transaction(string hex)except +
        hive_operation_handle cpp_deserialize_operation(string hex)except +

        vector[string]        cpp_op_impacted_accounts(hive_operation_handle op_handle)except +
        string                     cpp_op_to_binary(hive_operation_handle op_handle, bool use_hf26_serialization)except +
        binary_data                     cpp_op_binary(hive_operation_handle op_handle, bool use_hf26_serialization)except +
        void                            cpp_op_validate(hive_operation_handle op_handle)except +
        required_authority_collection cpp_op_required_authorities(hive_operation_handle op_handle)except +

        void                            cpp_tx_add_operation(hive_transaction_handle tx_handle, hive_operation_handle op_handle)except +
        void                            cpp_tx_add_signature(hive_transaction_handle tx_handle, string signature)except +
        void                            cpp_tx_set_expiration(hive_transaction_handle tx_handle, string expiration)except +
        string                     cpp_tx_to_legacy_json(hive_transaction_handle tx_handle)except +
        string                     cpp_tx_to_binary(hive_transaction_handle tx_handle, bool use_hf26_serialization, bool strip_to_unsigned_transaction)except +
        string                     cpp_tx_to_json(hive_transaction_handle tx_handle)except +
        string                     cpp_tx_id(hive_transaction_handle tx_handle, bool use_hf26_serialization)except +
        binary_data                     cpp_tx_binary(hive_transaction_handle tx_handle, bool use_hf26_serialization, bool strip_to_unsigned_transaction)except +
        required_authority_collection cpp_tx_required_authorities(hive_transaction_handle tx_handle)except +
        vector[string]        cpp_tx_impacted_accounts(hive_transaction_handle tx_handle)except +
        vector[string]        cpp_tx_signature_keys(hive_transaction_handle tx_handle, string chain_id, bool use_hf26_serialization)except +
        string                     cpp_tx_sig_digest(hive_transaction_handle tx_handle, string chain_id, bool use_hf26_serialization)except +
        void                            cpp_tx_validate(hive_transaction_handle tx_handle)except +

        void cpp_tx_proto_to_api( object transaction ) except +
        void cpp_tx_api_to_proto( object transaction ) except +

        hive_transaction_handle cpp_create_transaction_handle( object transaction, bool is_protobuf ) except +
        hive_operation_handle cpp_create_operation_handle( object operation, bool is_protobuf ) except +
