[build-system]
requires = [
    "poetry-core>=1.1.0",
    "cython==3.0.12",
    "setuptools>=67.8.0",
    "poetry-dynamic-versioning>=0.22.0"
]
build-backend = "poetry_dynamic_versioning.backend"


[tool.poetry]
name = "wax"
version = "0.0.0"
description = ""
repository = "https://gitlab.syncad.com/hive/wax"
authors = []
packages = [{ include = "wax"}]
include = [
    "wax/_private/proto/*",
    "wax/api/*",
]
source = [
    { name = "PyPI", priority = "primary" },
    { name = "gitlab-schemas", url = "https://gitlab.syncad.com/api/v4/projects/362/packages/pypi/simple", priority = "supplemental" },
    { name = "gitlab-beekeepy", url = "https://gitlab.syncad.com/api/v4/projects/434/packages/pypi/simple", priority = "supplemental" },
]

[tool.poetry.build]
script = "build.py"
generate-setup-file = true

[tool.poetry.dependencies]
python = "^3.12"
protobuf = "4.24.4"
beekeepy = "0.0.1.dev395+ee5b8b2"
httpx = {extras = ["http2"], version = "0.23.3"}
loguru = "0.7.2"
python-dateutil = "2.8.2"
requests = "2.32.3"

[tool.poetry.dev-dependencies]
mypy = "1.11.2"
pre-commit = "2.21.0"
pytest = "8.3.5"
pytest-asyncio = "0.25.3"
pytest-xdist = "3.6.1"
types-setuptools = ">=67.8.0"
ruff = "0.6.5"
grpcio = "1.59.0"
mypy-protobuf = "3.5.0"
types-python-dateutil = "2.8.19.14"
types-protobuf = "4.24.0.3"
grpc-stubs = "1.53.0.2"
grpcio-tools = "1.59.0"

[tool.poetry.group.docs.dependencies]
mkdocs = "1.6.1"
mkdocstrings-python="1.16.11"
mkdocs-material = "9.6.14"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.poetry-dynamic-versioning]
enable = true
format-jinja = """
    {%- set dirty_postfix = '.dirty' if dirty else '' -%}
    {%- if distance == 0 and not dirty -%}
        {{ serialize_pep440(base, stage, revision) }}
    {%- elif revision is not none -%}
        {{ serialize_pep440(base, stage, revision + 1, dev=distance, metadata=[commit]) }}{{ dirty_postfix }}
    {%- else -%}
        {{ serialize_pep440(bump_version(base), stage, revision, dev=distance, metadata=[commit]) }}{{ dirty_postfix }}
    {%- endif -%}
"""

[tool.poetry-dynamic-versioning.substitution]
files = [
    "wax/__init__.py",
]

[tool.mypy]
mypy_path = "python"
strict = true
disallow_untyped_decorators = false

[[tool.mypy.overrides]]
module = "wax._private.proto.*"
ignore_missing_imports = true
follow_imports = "skip"
ignore_errors = true

[[tool.mypy.overrides]]
module = "wax.proto.*"
ignore_missing_imports = true
follow_imports = "skip"
ignore_errors = true

[[tool.mypy.overrides]]
module = "wax.api.collection"
ignore_missing_imports = true
follow_imports = "skip"
ignore_errors = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules/
select = ["ALL"]
ignore = [
    "D1", # missing docstring in public
    "D203", # 1 blank line required before class docstring; because we re using D211
    "D212", # Multi-line docstring summary should start at the first line; because we re using D213
    "D401", # First line of docstring should be in imperative mood
    "D413", # Missing blank line after last section
    "TRY003", # Avoid specifying long messages outside the exception class; too restrictive
    "ANN101",  # Missing annotation for self; makes no sense
    "ANN102",  # Missing annotation for cls; makes no sense
    "TD002", # Missing author in to-do; no need for that
    "TD003",  # Missing issue link on the line following this to-do; no need for that
    "SLF001",  # Private member accessed: {access}; too restrictive
    "COM812", # Trailing comma missing; handled by ruff formatter
    "EM",  # agreed not to use it in our convention
    "FIX", # can't have that enabled, as we treat ruff result as an error on CI
    "S101",  # Use of assert detected; too restrictive
    "S311", # Standard pseudo-random generator are not suitable for cryptographic purposes; mostly used in tests
    "S603", # `subprocess` call: check for execution of untrusted input; https://github.com/astral-sh/ruff/issues/4045
    "ISC001", # Implicitly concatenated string literals on one line; disabled because conflicts with ruff formatter
    "PLR2004", # Ignore "magic value used in comparison" warnings; explicit constants not always necessary in tests
]

[tool.ruff.lint.per-file-ignores]
"**/sync_api.py" = [
  "PLR0913", # api definitions can have as many arguments as they need
  "FBT001", # api definitions have own argument restrictions
  "FBT002", # api definitions have own argument restrictions
  "TCH001",
  "TCH002",
]
"**/async_api.py" = [
  "PLR0913", # api definitions can have as many arguments as they need
  "FBT001", # api definitions have own argument restrictions
  "FBT002", # api definitions have own argument restrictions
  "TCH001",
  "TCH002",
]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.isort]
known-first-party = ["wax", "beekeepy"]
