//! Proc-macro companion of the `hiveio-wax` crate.
//!
//! Exposes the [`macro@hive_api`] attribute, re-exported by `hiveio-wax` as
//! `wax::hive_api`. Do not depend on this crate directly — the generated code
//! references `::wax::` items, so it only works together with that crate.

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::{format_ident, quote};
use syn::punctuated::Punctuated;
use syn::spanned::Spanned;
use syn::{
    Attribute, Error, Expr, ExprLit, Fields, FnArg, Ident, Item, ItemStruct,
    ItemTrait, Lit, LitStr, Meta, Pat, ReturnType, Token, TraitItem,
    TraitItemFn, Type,
};

/// Generates a typed Hive API surface from idiomatic declarations. See the
/// re-export documentation in the `hiveio-wax` crate (`wax::hive_api`) for
/// the full guide; in short:
///
/// On a **trait**, each `async fn name(params: P) -> R;` declaration becomes
/// a real `async fn` on a generated struct of the same name, calling the
/// JSON-RPC method `"<namespace>.<name>"` (namespace inferred from the trait
/// name, overridable with `#[hive_api(namespace = "...")]`). With
/// `#[hive_api(rest)]`, each method instead carries an HTTP verb attribute
/// (`#[get("/path/{param}")]`, `post`, `put`, `patch` or `delete`) and calls
/// the REST transport. Each method also emits its call descriptor as the
/// `SCREAMING_CASE` associated const and a `<name>_probe` constructor
/// building the health-check probe for `HealthChecker::register`; each
/// generated struct also gets `endpoint_url` / `set_endpoint_url` methods
/// reading and overriding the endpoint for its namespace alone.
///
/// On a **struct**, every field must be a surface generated by this
/// attribute; the struct becomes bindable itself, and one field may be
/// marked `#[hive_api(base)]` to also expose its surface through `Deref`.
#[proc_macro_attribute]
pub fn hive_api(attr: TokenStream, item: TokenStream) -> TokenStream {
    let expanded = parse_args(attr.into()).and_then(|args| {
        match syn::parse::<Item>(item)? {
            Item::Trait(item) => expand_trait(args, item),
            Item::Struct(item) => expand_struct(args, item),
            other => Err(Error::new(
                other.span(),
                "#[hive_api] must be applied to a trait (namespace surface) \
                 or a struct (composed surface)",
            )),
        }
    });

    expanded.unwrap_or_else(|e| e.to_compile_error()).into()
}

/// Represents the parsed `#[hive_api(...)]` arguments.
struct Args {
    rest: bool,
    namespace: Option<LitStr>,
}

/// Converts the attribute argument tokens (`rest`, `namespace = "..."`) into
/// [`Args`].
fn parse_args(attr: TokenStream2) -> syn::Result<Args> {
    let mut args = Args {
        rest: false,
        namespace: None,
    };
    if attr.is_empty() {
        return Ok(args);
    }

    let parser = Punctuated::<Meta, Token![,]>::parse_terminated;
    for meta in syn::parse::Parser::parse2(parser, attr)? {
        match &meta {
            Meta::Path(path) if path.is_ident("rest") => args.rest = true,
            Meta::NameValue(nv) if nv.path.is_ident("namespace") => {
                let Expr::Lit(ExprLit {
                    lit: Lit::Str(lit), ..
                }) = &nv.value
                else {
                    return Err(Error::new(
                        nv.value.span(),
                        "`namespace` expects a string literal",
                    ));
                };
                args.namespace = Some(lit.clone());
            }
            other => {
                return Err(Error::new(
                    other.span(),
                    "expected `rest` and/or `namespace = \"...\"`",
                ));
            }
        }
    }

    Ok(args)
}

/// Converts a CamelCase ident into the snake_case namespace name
/// (`CondenserApi` → `condenser_api`).
fn snake_case(ident: &Ident) -> String {
    let source = ident.to_string();
    let mut out = String::with_capacity(source.len() + 4);

    for (i, ch) in source.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }

    out
}

/// Converts an annotated trait into the namespace surface: a struct holding
/// the transport handle, its bind impl and one `async fn` per declaration.
fn expand_trait(args: Args, item: ItemTrait) -> syn::Result<TokenStream2> {
    if !item.generics.params.is_empty() || item.generics.where_clause.is_some()
    {
        return Err(Error::new(
            item.generics.span(),
            "#[hive_api] traits cannot be generic",
        ));
    }
    if !item.supertraits.is_empty() {
        return Err(Error::new(
            item.supertraits.span(),
            "#[hive_api] traits cannot have supertraits; compose surfaces \
             with a #[hive_api] struct instead",
        ));
    }
    if let Some(unsafety) = item.unsafety {
        return Err(Error::new(unsafety.span(), "remove `unsafe`"));
    }

    let namespace = args
        .namespace
        .as_ref()
        .map(LitStr::value)
        .unwrap_or_else(|| snake_case(&item.ident));

    let methods = item
        .items
        .iter()
        .map(|entry| {
            let TraitItem::Fn(method) = entry else {
                return Err(Error::new(
                    entry.span(),
                    "#[hive_api] traits may only contain `async fn` \
                     declarations",
                ));
            };

            expand_method(&namespace, method, args.rest)
        })
        .collect::<syn::Result<Vec<_>>>()?;

    let (caller, bind_trait) = if args.rest {
        (quote!(::wax::RestCaller), quote!(::wax::HiveRestApi))
    } else {
        (quote!(::wax::JsonRpcCaller), quote!(::wax::HiveApi))
    };

    let attrs = &item.attrs;
    let vis = &item.vis;
    let ident = &item.ident;
    let set_endpoint_doc = format!(
        "Routes every `{namespace}` call to `url` instead of the \
         transport's default endpoint; `None` clears the override. The \
         override lives on the shared transport, so every `{ident}` handle \
         bound to the same chain observes it."
    );
    let endpoint_doc = format!(
        "Returns the endpoint `{namespace}` calls currently resolve to — \
         the namespace override when set (see [`Self::set_endpoint_url`]), \
         else the transport's default endpoint."
    );

    Ok(quote! {
        #(#attrs)*
        #[derive(Clone)]
        #vis struct #ident {
            caller: #caller,
        }

        impl #bind_trait for #ident {
            fn bind(caller: #caller) -> Self {
                Self { caller }
            }
        }

        impl #ident {
            #[doc = #set_endpoint_doc]
            pub fn set_endpoint_url(
                &self,
                url: ::core::option::Option<::std::string::String>,
            ) {
                self.caller.set_endpoint_url_for_path(&[#namespace], url);
            }

            #[doc = #endpoint_doc]
            pub fn endpoint_url(&self) -> ::std::string::String {
                self.caller.endpoint_url_for_path(&[#namespace])
            }

            #(#methods)*
        }
    })
}

/// Converts one trait method declaration into the generated `async fn`.
fn expand_method(
    namespace: &str,
    method: &TraitItemFn,
    rest: bool,
) -> syn::Result<TokenStream2> {
    let sig = &method.sig;

    if sig.asyncness.is_none() {
        return Err(Error::new(
            sig.fn_token.span(),
            "declare API methods as `async fn`",
        ));
    }
    if let Some(body) = &method.default {
        return Err(Error::new(
            body.span(),
            "#[hive_api] methods are declarations — remove the body",
        ));
    }
    if !sig.generics.params.is_empty() || sig.generics.where_clause.is_some() {
        return Err(Error::new(
            sig.generics.span(),
            "#[hive_api] methods cannot be generic",
        ));
    }
    if sig.constness.is_some() || sig.unsafety.is_some() || sig.abi.is_some() {
        return Err(Error::new(
            sig.span(),
            "#[hive_api] methods support no qualifiers besides `async`",
        ));
    }
    if let Some(receiver) = sig.receiver() {
        return Err(Error::new(
            receiver.span(),
            "declare methods without `self` — #[hive_api] adds `&self` to \
             the generated method",
        ));
    }
    if sig.inputs.len() > 1 {
        return Err(Error::new(
            sig.inputs[1].span(),
            "#[hive_api] methods take at most one params argument (a single \
             `Serialize` value)",
        ));
    }

    let param = match sig.inputs.first() {
        None => None,
        Some(FnArg::Typed(arg)) => {
            let Pat::Ident(pat) = &*arg.pat else {
                return Err(Error::new(
                    arg.pat.span(),
                    "the params argument must be a plain identifier",
                ));
            };
            Some((pat.ident.clone(), (*arg.ty).clone()))
        }
        // Unreachable: a receiver was rejected above.
        Some(receiver) => {
            return Err(Error::new(receiver.span(), "unsupported argument"));
        }
    };
    let params_sig = param.as_ref().map(|(ident, ty)| quote!(, #ident: #ty));
    let params_expr = param
        .as_ref()
        .map_or(quote!(()), |(ident, _)| quote!(#ident));

    let result: Type = match &sig.output {
        ReturnType::Default => syn::parse_quote!(()),
        ReturnType::Type(_, ty) => (**ty).clone(),
    };

    let name = &sig.ident;
    let (verbs, attrs): (Vec<_>, Vec<_>) =
        method.attrs.iter().partition(|a| verb(a).is_some());

    let method_name = LitStr::new(&name.to_string(), name.span());
    let const_ident =
        Ident::new(&name.to_string().to_ascii_uppercase(), name.span());
    let const_doc = format!(
        "Used to address [`Self::{name}`] on the wire; also feeds \
                 health-check probes ([`Self::{name}_probe`])."
    );
    let probe_ident = format_ident!("{}_probe", name);
    let probe_doc = format!(
        "Builds a health-check probe calling [`Self::{name}`] with \
                 these params against the node URL chosen by the health \
                 checker; register it with `HealthChecker::register`."
    );

    let (descriptor, body, probe_body) = if rest {
        let (verb_name, path) = match verbs.as_slice() {
            [attr] => (verb(attr).unwrap(), rest_path(attr)?),
            [] => {
                return Err(Error::new(
                    sig.span(),
                    "REST methods need an HTTP verb attribute, e.g. \
                     #[get(\"/path/{param}\")]",
                ));
            }
            [_, second, ..] => {
                return Err(Error::new(
                    second.span(),
                    "REST methods take exactly one HTTP verb attribute",
                ));
            }
        };

        (
            quote! {
                pub const #const_ident: ::wax::RestCallDescriptor =
                    ::wax::RestCallDescriptor {
                        method: #verb_name,
                        path_template: #path,
                        namespace_path: &[#namespace, #method_name],
                    };
            },
            quote!(self.caller.call(&Self::#const_ident, #params_expr).await),
            quote!(::wax::healthchecker::ApiProbe::rest(
                ::core::clone::Clone::clone(&self.caller),
                Self::#const_ident,
                #params_expr,
            )),
        )
    } else {
        if let Some(attr) = verbs.first() {
            return Err(Error::new(
                attr.span(),
                "HTTP verb attributes require #[hive_api(rest)] on the \
                 trait",
            ));
        }

        let wire_name =
            LitStr::new(&format!("{namespace}.{name}"), name.span());

        (
            quote! {
                pub const #const_ident: ::wax::JsonRpcCallDescriptor =
                    ::wax::JsonRpcCallDescriptor {
                        method: #wire_name,
                        namespace_path: &[#namespace, #method_name],
                    };
            },
            quote!(self.caller.call(&Self::#const_ident, #params_expr).await),
            quote!(::wax::healthchecker::ApiProbe::json_rpc(
                ::core::clone::Clone::clone(&self.caller),
                Self::#const_ident,
                #params_expr,
            )),
        )
    };

    Ok(quote! {
        #[doc = #const_doc]
        #descriptor

        #(#attrs)*
        pub async fn #name(
            &self
            #params_sig
        ) -> ::core::result::Result<#result, ::wax::WaxChainError> {
            #body
        }

        #[doc = #probe_doc]
        pub fn #probe_ident(
            &self
            #params_sig
        ) -> ::wax::healthchecker::ApiProbe<#result> {
            #probe_body
        }
    })
}

/// Converts a method attribute into its uppercase HTTP verb, if it is one.
fn verb(attr: &Attribute) -> Option<&'static str> {
    ["get", "post", "put", "patch", "delete"]
        .iter()
        .find(|name| attr.path().is_ident(name))
        .map(|name| match *name {
            "get" => "GET",
            "post" => "POST",
            "put" => "PUT",
            "patch" => "PATCH",
            _ => "DELETE",
        })
}

/// Converts a verb attribute into its validated path-template literal.
fn rest_path(attr: &Attribute) -> syn::Result<LitStr> {
    let lit: LitStr = attr.parse_args().map_err(|_| {
        Error::new(
            attr.span(),
            "the verb attribute expects one string literal, e.g. \
             #[get(\"/path/{param}\")]",
        )
    })?;
    let path = lit.value();

    if !path.is_empty() && !path.starts_with('/') {
        return Err(Error::new(
            lit.span(),
            "the path template must start with `/` (it is appended to the \
             endpoint URL)",
        ));
    }

    // Placeholders are substituted from the params at runtime; malformed
    // braces would silently produce a broken URL there, so reject them here.
    let mut placeholder: Option<usize> = None;
    for ch in path.chars() {
        match (ch, &mut placeholder) {
            ('{', None) => placeholder = Some(0),
            ('{', Some(_)) => {
                return Err(Error::new(
                    lit.span(),
                    "nested `{` in path template",
                ));
            }
            ('}', None) => {
                return Err(Error::new(
                    lit.span(),
                    "unmatched `}` in path template",
                ));
            }
            ('}', Some(0)) => {
                return Err(Error::new(
                    lit.span(),
                    "empty `{}` placeholder in path template",
                ));
            }
            ('}', Some(_)) => placeholder = None,
            (_, Some(count)) => *count += 1,
            _ => {}
        }
    }
    if placeholder.is_some() {
        return Err(Error::new(lit.span(), "unmatched `{` in path template"));
    }

    Ok(lit)
}

/// Converts an annotated struct into a composed surface: a bind impl
/// constructing every field from one shared transport handle, plus `Deref`
/// to the field marked `#[hive_api(base)]`.
fn expand_struct(
    args: Args,
    mut item: ItemStruct,
) -> syn::Result<TokenStream2> {
    if let Some(namespace) = &args.namespace {
        return Err(Error::new(
            namespace.span(),
            "`namespace` applies to traits only",
        ));
    }
    if !item.generics.params.is_empty() || item.generics.where_clause.is_some()
    {
        return Err(Error::new(
            item.generics.span(),
            "#[hive_api] structs cannot be generic",
        ));
    }
    let Fields::Named(fields) = &mut item.fields else {
        return Err(Error::new(
            item.fields.span(),
            "#[hive_api] structs need named fields",
        ));
    };

    let (caller, bind_trait) = if args.rest {
        (quote!(::wax::RestCaller), quote!(::wax::HiveRestApi))
    } else {
        (quote!(::wax::JsonRpcCaller), quote!(::wax::HiveApi))
    };

    let mut base: Option<(Ident, Type)> = None;
    let mut binds = Vec::new();
    for field in &mut fields.named {
        let ident = field.ident.clone().expect("named field");
        let ty = field.ty.clone();

        // Extract (and strip — it is no plain Rust) the `base` marker.
        let mut marker = None;
        field.attrs.retain(|attr| {
            let ours = attr.path().is_ident("hive_api");
            if ours {
                marker = Some(attr.clone());
            }
            !ours
        });
        if let Some(marker) = marker {
            let arg = marker.parse_args::<Ident>();
            if !arg.map(|arg| arg == "base").unwrap_or(false) {
                return Err(Error::new(
                    marker.span(),
                    "the only field marker is #[hive_api(base)]",
                ));
            }
            if let Some((existing, _)) = &base {
                return Err(Error::new(
                    ident.span(),
                    format!("`{existing}` is already the base surface"),
                ));
            }
            base = Some((ident.clone(), ty.clone()));
        }

        binds.push(quote! {
            #ident: <#ty as #bind_trait>::bind(
                ::core::clone::Clone::clone(&caller),
            ),
        });
    }

    let ident = &item.ident;
    let deref = base.map(|(base_ident, base_ty)| {
        quote! {
            impl ::core::ops::Deref for #ident {
                type Target = #base_ty;

                fn deref(&self) -> &Self::Target {
                    &self.#base_ident
                }
            }
        }
    });

    Ok(quote! {
        #item

        impl #bind_trait for #ident {
            fn bind(caller: #caller) -> Self {
                Self {
                    #(#binds)*
                }
            }
        }

        #deref
    })
}
