use rust_decimal::Decimal;
use wax_core::{RustOperation, proto};

use crate::WaxError;
use crate::foundation::WaxFoundation;
use crate::models::authority::{AccountAuthorityInfo, RequiredAuthorities};
use crate::models::basic::{AccountName, Hex, PublicKey, Signature, SigDigest, TransactionId};
use crate::result::{BinaryViewOutputData, MinimizeRequiredSignaturesData};

pub trait Manabar {
    fn max_mana(&self) -> i64;
    fn current_mana(&self) -> i64;
    fn percent(&self) -> Decimal;
}

pub trait AuthorityDataProvider {
    fn get_account_authorities(&self, account: &str) -> Result<AccountAuthorityInfo, WaxError>;

    fn get_witness_public_key(&self, _witness: &str) -> Result<Option<PublicKey>, WaxError> {
        Ok(None)
    }
}

/// Offline wallet abstraction. Implementors hold private keys (or proxy a wallet
/// daemon) and expose digest signing plus memo-style data encryption.
pub trait SignatureProvider {
    /// Sign a transaction `sig_digest` with the private key matching `public_key`.
    ///
    /// `public_key` is a WIF-format key string; `sig_digest` is a hex string
    /// produced by [`Transaction::sig_digest`] (or its legacy variant).
    fn sign_digest(&self, public_key: &str, sig_digest: &str) -> Result<Signature, WaxError>;

    /// Encrypt `content` for the holder of `key` (and optionally `other_key`,
    /// when the message is also addressed to a third party).
    ///
    /// `nonce` may be passed to make encryption deterministic; otherwise a
    /// fresh nonce is generated by the provider. The returned string is a
    /// base58-encoded encrypted buffer suitable for use as a memo payload.
    fn encrypt_data(
        &self,
        content: &str,
        key: &str,
        other_key: Option<&str>,
        nonce: Option<u64>,
    ) -> Result<String, WaxError>;

    /// Decrypt a base58-encoded buffer previously produced by [`Self::encrypt_data`].
    ///
    /// `key` (and optionally `other_key`) identifies which private key(s) in
    /// the underlying container should be used to decrypt the payload.
    fn decrypt_data(
        &self,
        content: &str,
        key: &str,
        other_key: Option<&str>,
    ) -> Result<String, WaxError>;
}

pub trait Operation {
    fn validate(&self) -> Result<(), WaxError>;
    fn impacted_accounts(&self) -> Result<Vec<AccountName>, WaxError>;
}

pub trait OperationBuilder {
    fn finalize(self, foundation: &dyn WaxFoundation)
        -> Result<Vec<proto::Operation>, WaxError>;
}

pub trait Transaction {
    fn push_operation(self, op: RustOperation) -> Self;
    fn add_signature(&mut self, signature: &str) -> Result<(), WaxError>;
    fn set_expiration(&mut self, expiration: &str) -> Result<(), WaxError>;
    fn is_signed(&self) -> bool;
    fn validate(&self) -> Result<(), WaxError>;
    fn sig_digest(&self) -> Result<SigDigest, WaxError>;
    fn legacy_sig_digest(&self) -> Result<SigDigest, WaxError>;
    fn id(&self) -> Result<TransactionId, WaxError>;
    fn legacy_id(&self) -> Result<TransactionId, WaxError>;
    fn to_binary_form(&self, strip_to_unsigned: bool) -> Result<Hex, WaxError>;
    /// Returns the HF26 binary view: the wire-form hex plus a parsed AST
    /// annotating each byte range with its field name and type.
    fn binary_view_metadata(&self) -> Result<BinaryViewOutputData, WaxError>;
    /// Legacy-serialization counterpart to [`Self::binary_view_metadata`].
    fn legacy_binary_view_metadata(&self) -> Result<BinaryViewOutputData, WaxError>;
    fn to_api(&self) -> Result<String, WaxError>;
    fn to_legacy_api(&self) -> Result<String, WaxError>;
    fn signature_keys(&self) -> Result<Vec<PublicKey>, WaxError>;
    fn legacy_signature_keys(&self) -> Result<Vec<PublicKey>, WaxError>;
    fn impacted_accounts(&self) -> Result<Vec<AccountName>, WaxError>;
    fn required_authorities(&self) -> Result<RequiredAuthorities, WaxError>;
    fn collect_signing_keys(
        &self,
        provider: &dyn AuthorityDataProvider,
    ) -> Result<Vec<PublicKey>, WaxError>;
    fn minimize_required_signatures(
        &self,
        data: &MinimizeRequiredSignaturesData,
        provider: &dyn AuthorityDataProvider,
    ) -> Result<Vec<PublicKey>, WaxError>;
    fn transaction(&self) -> &proto::Transaction;
    fn push_builder(
        self,
        foundation: &dyn WaxFoundation,
        builder: impl OperationBuilder,
    ) -> Result<Self, WaxError>
    where
        Self: Sized;

    /// Convenience: compute the transaction's `sig_digest`, ask `wallet` to
    /// sign it with the private key matching `public_key`, append the result
    /// to this transaction, and return it.
    ///
    /// To sign with multiple keys, call this once per key.
    fn sign(
        &mut self,
        wallet: &dyn SignatureProvider,
        public_key: &str,
    ) -> Result<Signature, WaxError>;

    /// Open an encryption range. Operations pushed (or already at) the
    /// current end of the transaction will be encrypted by the next
    /// `perform_operation_encryption` call. Multiple ranges may be opened
    /// sequentially, each with its own key(s).
    ///
    /// `main_key` is the principal recipient public key; `other_key` is an
    /// optional second recipient (memo-style two-party encryption).
    fn start_encrypt(self, main_key: &str, other_key: Option<&str>) -> Self
    where
        Self: Sized;

    /// Close the most recently opened encryption range. Errors if no range is
    /// open or the latest range is already closed.
    fn stop_encrypt(self) -> Result<Self, WaxError>
    where
        Self: Sized;

    /// Walk each tracked encryption range and encrypt the memo-style field on
    /// the operations it covers, using `wallet.encrypt_data` with the range's
    /// keys and the transaction's `ref_block_prefix` as the nonce. The C++
    /// transaction handle is rebuilt from the mutated proto, and all ranges
    /// are cleared on success.
    ///
    /// The affected fields are: `transfer.memo`, `transfer_to_savings.memo`,
    /// `transfer_from_savings.memo`, `recurrent_transfer.memo`, `comment.body`,
    /// and `custom_json.json` (which is wrapped as `{"encrypted": "<ciphertext>"}`).
    /// Operations without an encryptable field are skipped silently.
    fn perform_operation_encryption(
        &mut self,
        wallet: &dyn SignatureProvider,
    ) -> Result<(), WaxError>;

    /// Walk every operation on the transaction and, for memo-style fields whose
    /// value starts with `#` (the encrypted marker used by hived), decrypt it
    /// via `wallet.decrypt_data`. Plaintext fields and operations without an
    /// encryptable field are left untouched. The C++ transaction handle is
    /// rebuilt from the mutated proto on success.
    fn decrypt(&mut self, wallet: &dyn SignatureProvider) -> Result<(), WaxError>;
}
