//! Hive blockchain library: transaction building, operation construction,
//! asset math, authority handling and validation, plus chain-bound operations
//! over JSON-RPC/REST endpoints.
//!
//! The offline entry point is [`create_wax_foundation`], which returns a
//! [`WaxFoundation`] exposing the offline API surface. The online entry point
//! is [`create_hive_chain`], which returns a [`HiveChain`] that also derefs
//! to [`WaxFoundation`]. The most common items can be imported at once
//! through the [`prelude`].

// The code generated by `#[hive_api]` references this crate as `::wax`,
// which inside the crate itself (e.g. `DefaultHiveApi`) only resolves
// through this self re-registration.
extern crate self as wax;

// NOTE: `mod core` shadows the built-in `core` crate in this root module;
// always write `crate::core::...` (never bare `core::...`) in this file.
#[doc(hidden)]
pub mod core;

mod base;
mod chain;

pub mod prelude;

pub use crate::core::proto;
pub use crate::core::transaction_to_canonical_json;
pub use base::*;
pub use chain::*;

/// Generates a typed Hive API surface from idiomatic declarations, for use
/// with [`extend`](chain::HiveChain::extend) /
/// [`extend_rest`](chain::HiveChain::extend_rest).
///
/// This is the Rust analog of declaring a `YourApi` type for TS
/// `extend<YourApi>()`. On a **trait**, the attribute consumes the
/// declaration and emits a struct of the same name with one real `async fn`
/// per method — so rust-analyzer autocompletes them with the forwarded doc
/// comments, and params/results are type-checked. Each
/// `async fn name(params: P) -> R;` calls the JSON-RPC method
/// `"<namespace>.<name>"`; the namespace is the snake_cased trait name,
/// overridable with `#[hive_api(namespace = "...")]`. `P` must implement
/// `serde::Serialize` and `R` `serde::de::DeserializeOwned`.
///
/// TS NOTE: the type-level `responseArray` knob of `TWaxApiRequest` is not
/// ported — it only lifts the declared element type into `ResultType[]` for
/// endpoints returning bare JSON arrays, working around the TS descriptor
/// indirection. Rust declares such a method naturally:
/// `async fn m(params: P) -> Vec<Item>;`.
///
/// Every generated struct carries a `set_endpoint_url(Option<String>)`
/// method routing that namespace's calls to an explicit endpoint — the TS
/// `api.<namespace>.endpointUrl = url` surface; a root-level override
/// covering a whole transport is
/// [`JsonRpcCaller::set_endpoint_url_for_path`] /
/// [`RestCaller::set_endpoint_url_for_path`] with an empty path.
///
/// Every method additionally emits its call descriptor
/// ([`JsonRpcCallDescriptor`] / [`RestCallDescriptor`]) as the
/// `SCREAMING_CASE` associated const of the same name, plus a
/// `<name>_probe(params)` constructor returning the [`ApiProbe`] that
/// [`HealthChecker::register`](HealthChecker::register) takes — so wiring a
/// generated method into the health checker is one call:
/// `checker.register(api.block_api.get_block_probe(params), vec![])`.
/// (Probe constructors additionally need `P: Send + Sync + 'static` and
/// `R: Send + 'static`.)
///
/// On a **struct**, every field must be a surface generated by this
/// attribute; the struct becomes bindable itself and one field may be marked
/// `#[hive_api(base)]` to also expose its surface through `Deref` — the
/// analog of the TS `TDefaultHiveApi & YourApi` intersection:
///
/// ```no_run
/// use wax::{create_hive_chain, hive_api};
///
/// /// Condenser plugin surface not shipped in the default API set.
/// #[hive_api]
/// pub trait CondenserApi {
///     /// Returns the number of accounts on the chain.
///     async fn get_account_count(params: Vec<String>) -> u64;
/// }
///
/// /// The custom namespace plus the default surface.
/// #[hive_api]
/// pub struct MyApi {
///     pub condenser_api: CondenserApi,
///     #[hive_api(base)]
///     base: wax::DefaultHiveApi,
/// }
///
/// # async fn demo() -> Result<(), wax::WaxChainError> {
/// let chain = create_hive_chain(None)?;
/// let api = chain.extend::<MyApi>();
///
/// let count = api.condenser_api.get_account_count(vec![]).await?;
/// let dgp = api
///     .database_api // `DefaultHiveApi` namespace, through `Deref`
///     .get_dynamic_global_properties(Default::default())
///     .await?;
/// # Ok(())
/// # }
/// ```
///
/// With `#[hive_api(rest)]`, the trait declares a REST surface for
/// [`extend_rest`](chain::HiveChain::extend_rest) instead: every method carries
/// an HTTP verb attribute whose path template is validated at compile time,
/// and `{placeholders}` are substituted from the params at call time:
///
/// ```no_run
/// # use wax::hive_api;
/// use wax::api::{ApiBlock, GetBlockRequest};
///
/// #[hive_api(rest, namespace = "hafah_api")]
/// pub trait HafahApi {
///     /// Fetches a block by number; `{block_num}` is filled from `params`.
///     #[get("/hafah-api/blocks/{block_num}")]
///     async fn get_block(params: GetBlockRequest) -> ApiBlock;
/// }
/// ```
pub use wax_macros::hive_api;
